// ============================================
// 1. LUCK - Daily Vibe (50 組)
// ============================================
const dailyVibePool = [
    { type: "super-lucky", icon: "😎", headline: "Jackpot Energy", level: "★★★★★", content: "You are the main character today. The spotlight is on you, and everything you touch turns to gold.", num: "777", color: "Royal Gold", item: "Crown" },
    { type: "super-lucky", icon: "😎", headline: "Unstoppable", level: "★★★★★", content: "Obstacles? What obstacles? You will glide through the day with zero resistance.", num: "100", color: "Victory Red", item: "Trophy" },
    { type: "super-lucky", icon: "😎", headline: "Money Magnet", level: "★★★★★", content: "Check your pockets, your emails, or the ground. Unexpected financial luck is heading your way.", num: "888", color: "Emerald Green", item: "Wallet" },
    { type: "super-lucky", icon: "😎", headline: "Star Power", level: "★★★★★", content: "Your charisma is at max level. Ask for that favor or make that date. They cannot say no to you.", num: "1", color: "Sparkling Silver", item: "Mirror" },
    { type: "super-lucky", icon: "😎", headline: "Perfect Timing", level: "★★★★★", content: "You will be in exactly the right place at the right time. Destiny is arranging a wonderful surprise.", num: "1111", color: "Cosmic Blue", item: "Watch" },
    { type: "good-vibes", icon: "😊", headline: "Small Win", level: "★★★★☆", content: "You will find a great parking spot, or the bus will arrive just as you walk up. Savour the convenience.", num: "66", color: "Asphalt Grey", item: "Keys" },
    { type: "good-vibes", icon: "😊", headline: "Tasty Treat", level: "★★★★☆", content: "The best meal of the week happens today. Don't feel guilty, just enjoy every single bite.", num: "3", color: "Creamy Beige", item: "Spoon" },
    { type: "good-vibes", icon: "😊", headline: "Friendship Boost", level: "★★★★☆", content: "Reach out to an old friend. The conversation will recharge your soul and bring good news.", num: "2", color: "Warm Orange", item: "Phone" },
    { type: "good-vibes", icon: "😊", headline: "Idea Machine", level: "★★★★☆", content: "Your brain is sharp today. That problem you've been stuck on? You'll solve it before lunch.", num: "99", color: "Electric Yellow", item: "Lightbulb" },
    { type: "good-vibes", icon: "😊", headline: "Good Hair Day", level: "★★★★☆", content: "You look fantastic today. Take a selfie, update your profile picture, and show off a little.", num: "5", color: "Glossy Black", item: "Comb" },
    { type: "good-vibes", icon: "😊", headline: "Smooth Sailing", level: "★★★★☆", content: "No drama, no stress. Just a peaceful, productive day where everything goes according to plan.", num: "24", color: "Ocean Blue", item: "Boat" },
    { type: "good-vibes", icon: "😊", headline: "Music Therapy", level: "★★★★☆", content: "The right song will come on at the perfect moment. Put your headphones on and vibe.", num: "33", color: "Melody Purple", item: "Headphones" },
    { type: "good-vibes", icon: "😊", headline: "Shopping Luck", level: "★★★★☆", content: "If you go shopping today, you will find exactly what you want on sale. It’s meant to be.", num: "50", color: "Sale Red", item: "Bag" },
    { type: "good-vibes", icon: "😊", headline: "Pet Therapy", level: "★★★★☆", content: "A cute animal will cross your path. Pet it for an instant boost of serotonin and luck.", num: "4", color: "Furry Brown", item: "Dog Bone" },
    { type: "good-vibes", icon: "😊", headline: "Green Light", level: "★★★★☆", content: "Traffic lights will turn green for you. The path forward is open, so keep moving.", num: "6", color: "Go Green", item: "Sneakers" },
    { type: "good-vibes", icon: "😊", headline: "Compliment", level: "★★★★☆", content: "Someone is noticing your hard work or your style. Expect a genuine compliment today.", num: "88", color: "Blush Pink", item: "Ribbon" },
    { type: "good-vibes", icon: "😊", headline: "Found It", level: "★★★★☆", content: "Something you thought was lost or forgotten will reappear. Keep your eyes open.", num: "7", color: "Dusty Gold", item: "Magnifying Glass" },
    { type: "good-vibes", icon: "😊", headline: "Creative Spark", level: "★★★★☆", content: "Write down your ideas. A fleeting thought today could become a big project tomorrow.", num: "11", color: "Ink Blue", item: "Pen" },
    { type: "good-vibes", icon: "😊", headline: "Comfort Zone", level: "★★★★☆", content: "Tonight is perfect for staying in. Blankets, movies, and snacks are your lucky ritual.", num: "22", color: "Cozy Grey", item: "Pillow" },
    { type: "good-vibes", icon: "😊", headline: "Kindness Loop", level: "★★★★☆", content: "Do a small favor for someone. The universe will pay you back double before the day ends.", num: "18", color: "Heart Red", item: "Candy" },
    { type: "gentle-reminder", icon: "😅", headline: "Battery Low", level: "★★☆☆☆", content: "Not your phone, but YOU. You are running on fumes. Go home early and recharge.", num: "10", color: "Dim Grey", item: "Bed" },
    { type: "gentle-reminder", icon: "😅", headline: "Hydrate Now", level: "★★☆☆☆", content: "Shaky senses you are dehydrated. Drink a glass of water immediately to restore your focus.", num: "2000", color: "Aqua Blue", item: "Bottle" },
    { type: "gentle-reminder", icon: "😅", headline: "Digital Detox", level: "★★☆☆☆", content: "Your eyes are tired from scrolling. Look at a tree or the sky for at least 5 minutes.", num: "5", color: "Forest Green", item: "Leaf" },
    { type: "gentle-reminder", icon: "😅", headline: "Watch Your Words", level: "★★☆☆☆", content: "Don't say the first thing that comes to mind. Silence is your best friend right now.", num: "9", color: "Silent White", item: "Mask" },
    { type: "gentle-reminder", icon: "😅", headline: "Save Money", level: "★★☆☆☆", content: "You don't need that expensive thing. Put your wallet away and wait 24 hours.", num: "24", color: "Budget Brown", item: "Piggy Bank" },
    { type: "gentle-reminder", icon: "😅", headline: "Posture Check", level: "★★☆☆☆", content: "Sit up straight! Shaky sees you slouching. Your back will thank you later.", num: "90", color: "Bone White", item: "Chair" },
    { type: "gentle-reminder", icon: "😅", headline: "Backup First", level: "★★☆☆☆", content: "Technology might betray you today. Save your files and double-check your work.", num: "2", color: "Safety Orange", item: "USB Drive" },
    { type: "gentle-reminder", icon: "😅", headline: "Umbrella Alert", level: "★★☆☆☆", content: "The weather is moody. Bring an umbrella even if it looks sunny. Trust me.", num: "95", color: "Rain Blue", item: "Umbrella" },
    { type: "gentle-reminder", icon: "😅", headline: "Clean Space", level: "★★☆☆☆", content: "Your room is messy, and so is your mind. Clean up your desk to clear your thoughts.", num: "15", color: "Clean White", item: "Trash Can" },
    { type: "gentle-reminder", icon: "😅", headline: "Don't Rush", level: "★★☆☆☆", content: "Haste makes waste today. Walk slower, eat slower, and check things twice.", num: "0", color: "Slow Green", item: "Turtle" },
    { type: "gentle-reminder", icon: "😅", headline: "Read the Room", level: "★★☆☆☆", content: "Someone around you is stressed. It's not the right time for jokes. Be observant.", num: "360", color: "Navy Blue", item: "Glasses" },
    { type: "gentle-reminder", icon: "😅", headline: "Call Home", level: "★★☆☆☆", content: "Your family misses you. A quick 5-minute call will bring good karma.", num: "60", color: "Warm Pink", item: "Home" },
    { type: "gentle-reminder", icon: "😅", headline: "Password Update", level: "★★☆☆☆", content: "It might be time to change that password you've used for 5 years. Stay safe online.", num: "123", color: "Cyber Black", item: "Lock" },
    { type: "gentle-reminder", icon: "😅", headline: "Check Expiry", level: "★★☆☆☆", content: "Check the food in your fridge. Something is about to go bad. Don't eat it.", num: "30", color: "Sour Yellow", item: "Fridge" },
    { type: "gentle-reminder", icon: "😅", headline: "Just Breathe", level: "★★☆☆☆", content: "You are holding tension in your shoulders. Drop them. Take a deep breath. Okay, carry on.", num: "8", color: "Air Blue", item: "Feather" },
    { type: "shaky-chaos", icon: "🤪", headline: "Potato Mode", level: "⚡⚡⚡", content: "Shaky is currently recharging. Please hold a potato for better signal quality.", num: "404", color: "Static Noise", item: "Potato" },
    { type: "shaky-chaos", icon: "🤪", headline: "Pigeon Spy", level: "⚡⚡⚡", content: "The pigeons are watching you. Do not make eye contact. Walk away slowly.", num: "007", color: "Pigeon Grey", item: "Bread Crumbs" },
    { type: "shaky-chaos", icon: "🤪", headline: "Glitch", level: "⚡⚡⚡", content: "Luck loading... 99%... ERROR. Please try dancing to fix the connection.", num: "500", color: "Glitch Purple", item: "Disco Ball" },
    { type: "shaky-chaos", icon: "🤪", headline: "Banana?", level: "⚡⚡⚡", content: "Shaky suggests you eat a banana. If you don't have one, just pretend you are holding one.", num: "12345", color: "Banana Yellow", item: "Invisible Banana" },
    { type: "shaky-chaos", icon: "🤪", headline: "Tin Foil Hat", level: "⚡⚡⚡", content: "They are listening to your thoughts. Think about kittens to confuse them.", num: "51", color: "Alien Green", item: "Foil" },
    { type: "shaky-chaos", icon: "🤪", headline: "Donut Panic", level: "⚡⚡⚡", content: "This is an emergency. You need a donut. Immediately. It is for your safety.", num: "911", color: "Sugar White", item: "Sprinkles" },
    { type: "shaky-chaos", icon: "🤪", headline: "Walk Backwards", level: "⚡⚡⚡", content: "To reset your luck, you must walk backwards through the next doorway. Do it.", num: "180", color: "Reverse Red", item: "Mirror" },
    { type: "shaky-chaos", icon: "🤪", headline: "Cat Mode", level: "⚡⚡⚡", content: "Ignore everyone today. Knock a glass off a table. Sleep in the sun. Be the cat.", num: "000", color: "Fur Orange", item: "Box" },
    { type: "shaky-chaos", icon: "🤪", headline: "Sock Mystery", level: "⚡⚡⚡", content: "The universe has stolen one of your socks. It was a sacrifice for good luck.", num: "42", color: "Lost Blue", item: "Single Sock" },
    { type: "shaky-chaos", icon: "🤪", headline: "Zombie Plan", level: "⚡⚡⚡", content: "Check your exits. You never know when the zombie apocalypse starts. Stay alert.", num: "666", color: "Rotten Green", item: "Bat" },
    { type: "shaky-chaos", icon: "🤪", headline: "No Pants", level: "⚡⚡⚡", content: "Shaky says pants are an illusion. (But please wear them if you go outside).", num: "321", color: "Skin Tone", item: "Shorts" },
    { type: "shaky-chaos", icon: "🤪", headline: "High Five", level: "⚡⚡⚡", content: "High five the next wall you see. It has been supporting you for years.", num: "555", color: "Wall White", item: "Hand" },
    { type: "shaky-chaos", icon: "🤪", headline: "Taco Tuesday", level: "⚡⚡⚡", content: "It doesn't matter what day it is. In your heart, it is Taco Tuesday.", num: "505", color: "Salsa Red", item: "Taco" },
    { type: "shaky-chaos", icon: "🤪", headline: "Scream", level: "⚡⚡⚡", content: "Go to a pillow and scream into it. It feels amazing. 10/10 recommend.", num: "314", color: "Loud Red", item: "Pillow" },
    { type: "shaky-chaos", icon: "🤪", headline: "System Reboot", level: "⚡⚡⚡", content: "You have been awake too long. Turn yourself off and on again (take a nap).", num: "403", color: "Black Screen", item: "Power Button" }
];

// ============================================
// 2. LUCK - Universe Says (50 組)
// ============================================
const universeSaysPool = [
    { type: "super-lucky", icon: "😎", headline: "11:11", level: "★★★★★", content: "Make a wish. The portal is open and the universe is listening to your exact thoughts right now.", num: "1111", color: "Portal White", item: "Clock" },
    { type: "super-lucky", icon: "😎", headline: "Infinite Flow", level: "★★★★★", content: "Abundance is rushing towards you like a waterfall. Prepare to receive more than you asked for.", num: "888", color: "Infinity Gold", item: "Figure 8" },
    { type: "super-lucky", icon: "😎", headline: "Mastery", level: "★★★★★", content: "You have learned the lesson. The universe is graduating you to the next level of success.", num: "33", color: "Master Blue", item: "Diploma" },
    { type: "super-lucky", icon: "😎", headline: "Miracle", level: "★★★★★", content: "A sudden, positive shift is happening. What seemed impossible yesterday is possible today.", num: "7777", color: "Miracle Pink", item: "Sparkle" },
    { type: "super-lucky", icon: "😎", headline: "The One", level: "★★★★★", content: "You are aligned with your highest purpose. Every step you take today is the right step.", num: "1", color: "Pure Light", item: "Sun" },
    { type: "good-vibes", icon: "😊", headline: "Feather", level: "★★★★☆", content: "If you see a feather today, it means your guardian angel is near and supporting you.", num: "444", color: "Angel White", item: "Feather" },
    { type: "good-vibes", icon: "😊", headline: "Harmony", level: "★★★★☆", content: "Things are coming into balance. Your mind, body, and spirit are syncing up.", num: "222", color: "Balance Green", item: "Scale" },
    { type: "good-vibes", icon: "😊", headline: "Change", level: "★★★★☆", content: "A positive change is on the horizon. Don't be afraid of the wind, let it carry you.", num: "555", color: "Wind Blue", item: "Leaf" },
    { type: "good-vibes", icon: "😊", headline: "Love Sign", level: "★★★★☆", content: "If you see two birds together, it is a sign that love (romantic or platonic) is strengthening.", num: "2", color: "Rose Pink", item: "Bird Pair" },
    { type: "good-vibes", icon: "😊", headline: "Creation", level: "★★★★☆", content: "You have the power to create your reality. Visualise what you want, and it will manifest.", num: "369", color: "Tesla Purple", item: "Crystal" },
    { type: "good-vibes", icon: "😊", headline: "Progress", level: "★★★★☆", content: "One step after another. You are climbing the mountain steadily. Keep looking up.", num: "123", color: "Mountain Grey", item: "Stairs" },
    { type: "good-vibes", icon: "😊", headline: "Completion", level: "★★★★☆", content: "A cycle is ending. Celebrate what you have achieved and prepare for a fresh start.", num: "99", color: "Sunset Orange", item: "Ring" },
    { type: "good-vibes", icon: "😊", headline: "Inner Voice", level: "★★★★☆", content: "Listen to the quiet voice inside you. It knows the way better than any map.", num: "108", color: "Spirit Violet", item: "Bell" },
    { type: "good-vibes", icon: "😊", headline: "Reflection", level: "★★★★☆", content: "The world is a mirror. Smile at it, and it will smile back at you today.", num: "24", color: "Mirror Silver", item: "Mirror" },
    { type: "good-vibes", icon: "😊", headline: "Growth", level: "★★★★☆", content: "Like a plant pushing through soil, you are growing stronger even if you can't see it yet.", num: "72", color: "Sprout Green", item: "Plant" },
    { type: "good-vibes", icon: "😊", headline: "Synchronicity", level: "★★★★☆", content: "Notice the coincidences. Hearing the same song or name twice is a message.", num: "1212", color: "Twin Yellow", item: "Notes" },
    { type: "good-vibes", icon: "😊", headline: "Stability", level: "★★★★☆", content: "You are safe and grounded. Build your foundation with confidence.", num: "4", color: "Earth Brown", item: "Brick" },
    { type: "good-vibes", icon: "😊", headline: "Adventure", level: "★★★★☆", content: "The universe wants you to explore. Take a different route or try a new flavor.", num: "101", color: "Map Beige", item: "Compass" },
    { type: "good-vibes", icon: "😊", headline: "Joy", level: "★★★★☆", content: "Laughter is the highest vibration. Find a reason to laugh out loud today.", num: "808", color: "Happy Orange", item: "Balloon" },
    { type: "good-vibes", icon: "😊", headline: "Clarity", level: "★★★★☆", content: "The fog is lifting. You will see the truth of a situation very clearly soon.", num: "2020", color: "Clear Blue", item: "Glasses" },
    { type: "gentle-reminder", icon: "😅", headline: "Red Light", level: "★★☆☆☆", content: "Stop. If you are hitting obstacles, take it as a sign to pause, not to push harder.", num: "0", color: "Stop Red", item: "Traffic Light" },
    { type: "gentle-reminder", icon: "😅", headline: "Echo", level: "★★☆☆☆", content: "Are you complaining? The universe will echo that energy back. Change your words.", num: "30", color: "Echo Grey", item: "Megaphone" },
    { type: "gentle-reminder", icon: "😅", headline: "Shadow", level: "★★☆☆☆", content: "Don't ignore the difficult feelings. They are trying to teach you something important.", num: "9", color: "Shadow Black", item: "Moon" },
    { type: "gentle-reminder", icon: "😅", headline: "Knot", level: "★★☆☆☆", content: "Your energy is tangled. Stretch your body or meditate to release the knots.", num: "88", color: "Rope Brown", item: "Knot" },
    { type: "gentle-reminder", icon: "😅", headline: "Storm", level: "★★☆☆☆", content: "Clouds are gathering. It's okay to stay inside and protect your energy today.", num: "10", color: "Storm Grey", item: "Umbrella" },
    { type: "gentle-reminder", icon: "😅", headline: "Silence", level: "★★☆☆☆", content: "When the universe is silent, it means 'Wait'. Don't force an answer.", num: "00", color: "Silent White", item: "Earplugs" },
    { type: "gentle-reminder", icon: "😅", headline: "Detour", level: "★★☆☆☆", content: "Your path might change unexpectedly. Accept the detour, it avoids a cliff.", num: "50", color: "Warning Orange", item: "Cone" },
    { type: "gentle-reminder", icon: "😅", headline: "Leak", level: "★★☆☆☆", content: "You are leaking energy on people who don't deserve it. Plug the hole.", num: "25", color: "Water Blue", item: "Cork" },
    { type: "gentle-reminder", icon: "😅", headline: "Gravity", level: "★★☆☆☆", content: "You are feeling heavy. Put down the emotional baggage you are carrying.", num: "100", color: "Heavy Metal", item: "Weight" },
    { type: "gentle-reminder", icon: "😅", headline: "Rewind", level: "★★☆☆☆", content: "You missed a detail. Go back and check your work or your message again.", num: "4", color: "Tape Black", item: "Button" },
    { type: "gentle-reminder", icon: "😅", headline: "Fog", level: "★★☆☆☆", content: "Visibility is low. Do not make big decisions until the sun comes out.", num: "15", color: "Fog White", item: "Lamp" },
    { type: "gentle-reminder", icon: "😅", headline: "Alert", level: "★★☆☆☆", content: "Pay attention to your surroundings. Being distracted today could be costly.", num: "911", color: "Alert Red", item: "Siren" },
    { type: "gentle-reminder", icon: "😅", headline: "Slow Down", level: "★★☆☆☆", content: "You are running faster than your soul can keep up. Walk.", num: "5", color: "Turtle Green", item: "Shell" },
    { type: "gentle-reminder", icon: "😅", headline: "Disconnect", level: "★★☆☆☆", content: "The signal is weak. Unplug from the internet and reconnect with nature.", num: "408", color: "Offline Grey", item: "Tree" },
    { type: "gentle-reminder", icon: "😅", headline: "Balance", level: "★★☆☆☆", content: "You are giving too much and receiving too little. Restore the balance.", num: "5050", color: "Half Black", item: "Yin Yang" },
    { type: "shaky-chaos", icon: "🤪", headline: "Matrix Glitch", level: "⚡⚡⚡", content: "Did you see that cat twice? The matrix is glitching. Stay calm.", num: "10101", color: "Code Green", item: "Black Cat" },
    { type: "shaky-chaos", icon: "🤪", headline: "Flying Toast", level: "⚡⚡⚡", content: "The universe sends you a flying toaster. It means... absolutely nothing.", num: "1995", color: "Toast Brown", item: "Toaster" },
    { type: "shaky-chaos", icon: "🤪", headline: "Static", level: "⚡⚡⚡", content: "Krrrzzt... signal lost... please shake your device to restore cosmic order.", num: "0000", color: "Static Noise", item: "TV" },
    { type: "shaky-chaos", icon: "🤪", headline: "Teapot", level: "⚡⚡⚡", content: "Error 418: I am a teapot. I cannot tell your fortune, but I can make tea.", num: "418", color: "Porcelain White", item: "Teapot" },
    { type: "shaky-chaos", icon: "🤪", headline: "Rubber Duck", level: "⚡⚡⚡", content: "When in doubt, explain your problem to a rubber duck. It holds all wisdom.", num: "42", color: "Duck Yellow", item: "Duck" },
    { type: "shaky-chaos", icon: "🤪", headline: "Void", level: "⚡⚡⚡", content: "You stared into the void, and the void sent you a friend request.", num: "0", color: "Void Black", item: "Black Hole" },
    { type: "shaky-chaos", icon: "🤪", headline: "Pizza Signal", level: "⚡⚡⚡", content: "The stars have aligned to form a pepperoni pizza. Dinner is decided.", num: "8", color: "Cheese Yellow", item: "Pizza Box" },
    { type: "shaky-chaos", icon: "🤪", headline: "Wrong Number", level: "⚡⚡⚡", content: "Hello? Is this the universe? Sorry, you have the wrong number. Bye.", num: "867", color: "Telephone Red", item: "Phone" },
    { type: "shaky-chaos", icon: "🤪", headline: "Spaghetti", level: "⚡⚡⚡", content: "Your destiny is currently tangled like spaghetti. Add sauce and enjoy the mess.", num: "500", color: "Pasta Yellow", item: "Fork" },
    { type: "shaky-chaos", icon: "🤪", headline: "Blue Screen", level: "⚡⚡⚡", content: "Your luck has encountered a fatal error. Please restart your day.", num: "000", color: "BSOD Blue", item: "Computer" },
    { type: "shaky-chaos", icon: "🤪", headline: "Moon Cheese", level: "⚡⚡⚡", content: "The moon is not made of cheese, but Shaky wishes it was. That is the message.", num: "1969", color: "Moon Grey", item: "Cheese" },
    { type: "shaky-chaos", icon: "🤪", headline: "Dinosaur", level: "⚡⚡⚡", content: "If you see a dinosaur today, run. If not, have a nice day.", num: "65", color: "Fossil Brown", item: "Bone" },
    { type: "shaky-chaos", icon: "🤪", headline: "Loading", level: "⚡⚡⚡", content: "Buffering... Buffering... The universe is on dial-up internet today.", num: "56", color: "Modem Grey", item: "Cable" },
    { type: "shaky-chaos", icon: "🤪", headline: "Beware Squirrels", level: "⚡⚡⚡", content: "The squirrels are planning something. Shaky does not trust them.", num: "333", color: "Nut Brown", item: "Acorn" },
    { type: "shaky-chaos", icon: "🤪", headline: "Upside Down", level: "⚡⚡⚡", content: "˙uʍop ǝpısdn sı buıɥʇʎɹǝʌƎ ˙ʎɐpoʇ pɹıǝʍ sı ʎʇıʌɐɹD", num: "666", color: "Invert Black", item: "Bat" }
];

// ============================================
// 3. LUCK - Yes or No (50 組)
// ============================================
const yesOrNoPool = [
    { type: "super-lucky", icon: "😎", headline: "HELL YES", level: "★★★★★", content: "Don't even hesitate. The universe is rolling out the red carpet for you. Do it.", num: "1000", color: "Winning Gold", item: "Rocket" },
    { type: "super-lucky", icon: "😎", headline: "Destiny Calls", level: "★★★★★", content: "This is exactly what you are supposed to do. It is written in the stars.", num: "7777", color: "Cosmic Purple", item: "Star Map" },
    { type: "super-lucky", icon: "😎", headline: "Green Light", level: "★★★★★", content: "Full speed ahead! There are no police on this road. Just pure freedom and success.", num: "101", color: "Traffic Green", item: "Sports Car" },
    { type: "super-lucky", icon: "😎", headline: "Jackpot", level: "★★★★★", content: "The outcome will be even better than you imagine. Bet everything on Yes.", num: "999", color: "Casino Red", item: "Chip" },
    { type: "super-lucky", icon: "😎", headline: "Victory", level: "★★★★★", content: "You have already won. Now you just need to walk up and claim the prize.", num: "1", color: "Champion Gold", item: "Medal" },
    { type: "good-vibes", icon: "😊", headline: "Go For It", level: "★★★★☆", content: "Why not? It sounds like a fun idea and the risk is very low.", num: "10", color: "Sunny Yellow", item: "Balloon" },
    { type: "good-vibes", icon: "😊", headline: "Trust Gut", level: "★★★★☆", content: "Your intuition is screaming Yes. Stop overthinking and listen to that feeling.", num: "11", color: "Deep Blue", item: "Compass" },
    { type: "good-vibes", icon: "😊", headline: "Likely", level: "★★★★☆", content: "The odds are in your favor. It might require a little effort, but it will work.", num: "75", color: "Mint Green", item: "Dice" },
    { type: "good-vibes", icon: "😊", headline: "Sure Thing", level: "★★★★☆", content: "It’s a safe bet. Proceed with confidence and a smile.", num: "50", color: "Sky Blue", item: "Thumbs Up" },
    { type: "good-vibes", icon: "😊", headline: "Good Timing", level: "★★★★☆", content: "Now is a great time to start. The energy is flowing in the right direction.", num: "12", color: "Clock Orange", item: "Watch" },
    { type: "good-vibes", icon: "😊", headline: "Supportive", level: "★★★★☆", content: "Yes, and you will find people who want to help you along the way.", num: "22", color: "Hug Pink", item: "Friend" },
    { type: "good-vibes", icon: "😊", headline: "Smooth Path", level: "★★★★☆", content: "No major obstacles detected. It should be an easy and pleasant journey.", num: "6", color: "River Blue", item: "Boat" },
    { type: "good-vibes", icon: "😊", headline: "Worth It", level: "★★★★☆", content: "The reward is worth the effort. Do not be lazy today!", num: "100", color: "Rich Green", item: "Coin" },
    { type: "good-vibes", icon: "😊", headline: "Creative Yes", level: "★★★★☆", content: "Yes, but try to do it in a new, creative way. Don't be boring.", num: "9", color: "Paint Red", item: "Brush" },
    { type: "good-vibes", icon: "😊", headline: "Happy End", level: "★★★★☆", content: "The ending of this story is a happy one. You don't need to worry.", num: "88", color: "Story White", item: "Book" },
    { type: "good-vibes", icon: "😊", headline: "Small Yes", level: "★★★★☆", content: "A gentle yes. It won't change the world, but it will make you happy.", num: "5", color: "Tiny Pink", item: "Flower" },
    { type: "good-vibes", icon: "😊", headline: "Proceed", level: "★★★★☆", content: "All systems go. You have permission to proceed.", num: "18", color: "Steel Grey", item: "Key" },
    { type: "good-vibes", icon: "😊", headline: "Looks Good", level: "★★★★☆", content: "From Shaky's perspective, this looks like a solid plan.", num: "4", color: "Vision Violet", item: "Glasses" },
    { type: "good-vibes", icon: "😊", headline: "Open Door", level: "★★★★☆", content: "The door is unlocked. You just have to push it open.", num: "7", color: "Wood Brown", item: "Door Handle" },
    { type: "good-vibes", icon: "😊", headline: "Adventure", level: "★★★★☆", content: "Yes! Treat it like an adventure. It will be a fun story to tell later.", num: "33", color: "Map Yellow", item: "Boots" },
    { type: "gentle-reminder", icon: "😅", headline: "Wait", level: "★★☆☆☆", content: "Not right now. The timing is off. Ask again in 24 hours.", num: "24", color: "Pause Grey", item: "Hourglass" },
    { type: "gentle-reminder", icon: "😅", headline: "Too Risky", level: "★★☆☆☆", content: "The odds are against you. Shaky recommends you fold and save your money.", num: "13", color: "Warning Orange", item: "Shield" },
    { type: "gentle-reminder", icon: "😅", headline: "Sleep On It", level: "★★☆☆☆", content: "You are too emotional right now. Decide tomorrow morning after coffee.", num: "8", color: "Night Blue", item: "Pillow" },
    { type: "gentle-reminder", icon: "😅", headline: "Check Detail", level: "★★☆☆☆", content: "There is a hidden trap. Read the fine print before saying yes.", num: "2", color: "Ink Black", item: "Magnifier" },
    { type: "gentle-reminder", icon: "😅", headline: "Don't Force", level: "★★☆☆☆", content: "If you have to force it, it's not a Yes. Let it go.", num: "0", color: "Empty White", item: "Feather" },
    { type: "gentle-reminder", icon: "😅", headline: "Bad Timing", level: "★★☆☆☆", content: "Right idea, wrong time. Keep it in your pocket for next month.", num: "30", color: "Calendar Red", item: "Pocket" },
    { type: "gentle-reminder", icon: "😅", headline: "Reconsider", level: "★★☆☆☆", content: "Are you doing this for yourself or for someone else? Think about it.", num: "14", color: "Mirror Silver", item: "Mirror" },
    { type: "gentle-reminder", icon: "😅", headline: "Nope", level: "★★☆☆☆", content: "Just... no. You know why. Don't do it.", num: "20", color: "Stop Red", item: "X Sign" },
    { type: "gentle-reminder", icon: "😅", headline: "Save Energy", level: "★★☆☆☆", content: "This will drain your battery too much. Say no and take a nap instead.", num: "15", color: "Low Battery Grey", item: "Battery" },
    { type: "gentle-reminder", icon: "😅", headline: "Distraction", level: "★★☆☆☆", content: "This is just a distraction from your real goal. Focus on what matters.", num: "90", color: "Blurry Blue", item: "Target" },
    { type: "gentle-reminder", icon: "😅", headline: "Ask Friend", level: "★★☆☆☆", content: "Your judgment is cloudy. Ask your smartest friend for advice.", num: "3", color: "Phone Green", item: "Telephone" },
    { type: "gentle-reminder", icon: "😅", headline: "Too Expensive", level: "★★☆☆☆", content: "The cost (emotional or financial) is too high. Walk away.", num: "99", color: "Expensive Gold", item: "Empty Wallet" },
    { type: "gentle-reminder", icon: "😅", headline: "Complicated", level: "★★☆☆☆", content: "It’s not a simple Yes or No. It’s a 'Yes, but it will be a headache'.", num: "55", color: "Tangled Grey", item: "Knot" },
    { type: "gentle-reminder", icon: "😅", headline: "Missing Info", level: "★★☆☆☆", content: "You don't know the full story yet. Do more research.", num: "40", color: "Mystery Purple", item: "File" },
    { type: "gentle-reminder", icon: "😅", headline: "Safety First", level: "★★☆☆☆", content: "Take the safe option this time. Adventure can wait for the weekend.", num: "60", color: "Helmet Yellow", item: "Helmet" },
    { type: "shaky-chaos", icon: "🤪", headline: "Ask Mom", level: "⚡⚡⚡", content: "Shaky is scared to answer. Please ask your mother.", num: "1980", color: "Vintage Rose", item: "Apron" },
    { type: "shaky-chaos", icon: "🤪", headline: "Coin Flip", level: "⚡⚡⚡", content: "I cannot decide. Flip a coin. Heads = Yes, Tails = Pizza.", num: "5050", color: "Silver", item: "Coin" },
    { type: "shaky-chaos", icon: "🤪", headline: "Error 404", level: "⚡⚡⚡", content: "Answer not found. Check your internet connection or your brain.", num: "404", color: "Glitch Blue", item: "Dead Link" },
    { type: "shaky-chaos", icon: "🤪", headline: "Pizza", level: "⚡⚡⚡", content: "The answer is Pizza. It doesn't matter what the question was.", num: "8888", color: "Cheese Yellow", item: "Slice" },
    { type: "shaky-chaos", icon: "🤪", headline: "Run", level: "⚡⚡⚡", content: "Don't ask questions. Just run. Run now!", num: "000", color: "Fast Red", item: "Sneakers" },
    { type: "shaky-chaos", icon: "🤪", headline: "Aliens", level: "⚡⚡⚡", content: "The aliens say YES, but they also eat rocks. So... maybe?", num: "51", color: "UFO Green", item: "Rock" },
    { type: "shaky-chaos", icon: "🤪", headline: "Cat Says No", level: "⚡⚡⚡", content: "I asked the cat. The cat looked at me with disgust. That means No.", num: "9999", color: "Fur Black", item: "Cat Paw" },
    { type: "shaky-chaos", icon: "🤪", headline: "Forbidden", level: "⚡⚡⚡", content: "Access Denied. You are not high level enough for this answer.", num: "403", color: "Lock Red", item: "Gate" },
    { type: "shaky-chaos", icon: "🤪", headline: "Dance Off", level: "⚡⚡⚡", content: "If you can dance for 1 minute without stopping, the answer is Yes.", num: "123", color: "Disco Silver", item: "Speaker" },
    { type: "shaky-chaos", icon: "🤪", headline: "Silence", level: "⚡⚡⚡", content: "...... (Shaky is pretending not to hear you).", num: "00", color: "Silent White", item: "Earplugs" },
    { type: "shaky-chaos", icon: "🤪", headline: "Taco Time", level: "⚡⚡⚡", content: "Forget your question. Let's go get tacos.", num: "202", color: "Spicy Red", item: "Hot Sauce" },
    { type: "shaky-chaos", icon: "🤪", headline: "Maybe Baby", level: "⚡⚡⚡", content: "Maybe. Maybe not. Maybe you should buy Shaky a drink first.", num: "500", color: "Confused Purple", item: "Drink" },
    { type: "shaky-chaos", icon: "🤪", headline: "Potato", level: "⚡⚡⚡", content: "Potato. That is the only wisdom I have for you today.", num: "1010", color: "Potato Brown", item: "French Fry" },
    { type: "shaky-chaos", icon: "🤪", headline: "Loading...", level: "⚡⚡⚡", content: "Calculating answer... 1%... 2%... This might take a year. Ask later.", num: "300", color: "Slow Grey", item: "Snail" },
    { type: "shaky-chaos", icon: "🤪", headline: "Reboot", level: "⚡⚡⚡", content: "Shaky has crashed. Please turn your phone upside down to reset.", num: "503", color: "Black Screen", item: "Power Cord" }
];

// ============================================
// 4. LOVE - Love Radar (50 組) - Crush
// ============================================
const loveRadarPool = [
    { type: "super-lucky", icon: "😎", headline: "Cupid's Target", level: "★★★★★", content: "Bullseye! Cupid has hit the target. Prepare for a direct hit of romance very soon.", num: "100", color: "Hot Pink", item: "Arrow" },
    { type: "super-lucky", icon: "😎", headline: "Soulmate Alert", level: "★★★★★", content: "The radar is going crazy. A deep, spiritual connection is entering your orbit.", num: "222", color: "Deep Red", item: "Heart Pair" },
    { type: "super-lucky", icon: "😎", headline: "Magnetic", level: "★★★★★", content: "You are irresistible today. Everyone who looks at you will be charmed. Use this power wisely.", num: "520", color: "Magnet Purple", item: "Magnet" },
    { type: "super-lucky", icon: "😎", headline: "Big Yes", level: "★★★★★", content: "Thinking about confessing? Or waiting for a text? The answer is a massive YES.", num: "999", color: "Wedding White", item: "Ring" },
    { type: "super-lucky", icon: "😎", headline: "Love Bomb", level: "★★★★★", content: "Prepare for an explosion of affection, gifts, or compliments. You are loved.", num: "1314", color: "Rose Gold", item: "Bouquet" },
    { type: "good-vibes", icon: "😊", headline: "Cute Text", level: "★★★★☆", content: "Check your phone. A sweet message is on its way to brighten your day.", num: "3", color: "Message Blue", item: "Phone" },
    { type: "good-vibes", icon: "😊", headline: "Eye Contact", level: "★★★★☆", content: "Someone is looking at you when you aren't looking. Notice who it is.", num: "2020", color: "Vision Violet", item: "Glasses" },
    { type: "good-vibes", icon: "😊", headline: "Butterflies", level: "★★★★☆", content: "That nervous, excited feeling? Enjoy it. It's the best part of the beginning.", num: "88", color: "Spring Green", item: "Butterfly" },
    { type: "good-vibes", icon: "😊", headline: "Crush", level: "★★★★☆", content: "Your crush is thinking about you right now. Maybe telepathy is real.", num: "11", color: "Blush Pink", item: "Letter" },
    { type: "good-vibes", icon: "😊", headline: "Chemistry", level: "★★★★☆", content: "Sparks are flying. The conversation will flow effortlessly today.", num: "101", color: "Lab Blue", item: "Potion" },
    { type: "good-vibes", icon: "😊", headline: "Date Night", level: "★★★★☆", content: "Whether with a partner or yourself, tonight is perfect for romance and candles.", num: "7", color: "Wine Red", item: "Candle" },
    { type: "good-vibes", icon: "😊", headline: "Confidence", level: "★★★★☆", content: "Self-love is the best love potion. Wear your favorite outfit and shine.", num: "1", color: "Star Gold", item: "Mirror" },
    { type: "good-vibes", icon: "😊", headline: "Sweet Dream", level: "★★★★☆", content: "You will dream of someone special, or they will dream of you.", num: "24", color: "Moon Yellow", item: "Cloud" },
    { type: "good-vibes", icon: "😊", headline: "Match", level: "★★★★☆", content: "You and someone else are on the same wavelength. A perfect match.", num: "2", color: "Peach", item: "Puzzle Piece" },
    { type: "good-vibes", icon: "😊", headline: "Glow Up", level: "★★★★☆", content: "Love makes you beautiful. People will ask what skincare you are using.", num: "18", color: "Skin Beige", item: "Lipstick" },
    { type: "good-vibes", icon: "😊", headline: "Flirt", level: "★★★★☆", content: "Be a little playful today. A wink or a smile will go a long way.", num: "6", color: "Cheeky Red", item: "Wink Emoji" },
    { type: "good-vibes", icon: "😊", headline: "Secret Admirer", level: "★★★★☆", content: "There is someone in the background who really appreciates you.", num: "007", color: "Shadow Grey", item: "Mask" },
    { type: "good-vibes", icon: "😊", headline: "Safety", level: "★★★★☆", content: "This connection feels safe and warm. No games, just comfort.", num: "4", color: "Cozy Brown", item: "Blanket" },
    { type: "good-vibes", icon: "😊", headline: "New Chapter", level: "★★★★☆", content: "Turn the page. A new romantic story is about to begin.", num: "12", color: "Fresh Green", item: "Book" },
    { type: "good-vibes", icon: "😊", headline: "Surprise", level: "★★★★☆", content: "Unexpected kindness from a loved one will make your heart melt.", num: "50", color: "Gift Red", item: "Box" },
    { type: "gentle-reminder", icon: "😅", headline: "Slow Down", level: "★★☆☆☆", content: "You are moving too fast. Love is a marathon, not a sprint. Pace yourself.", num: "40", color: "Slow Yellow", item: "Snail" },
    { type: "gentle-reminder", icon: "😅", headline: "Self Love First", level: "★★☆☆☆", content: "You cannot pour from an empty cup. Love yourself before seeking it from others.", num: "100", color: "Solo White", item: "Cup" },
    { type: "gentle-reminder", icon: "😅", headline: "No Exes", level: "★★☆☆☆", content: "Do not text your ex. Put the phone down. Shaky is warning you.", num: "0", color: "Stop Red", item: "Trash Can" },
    { type: "gentle-reminder", icon: "😅", headline: "Mixed Signals", level: "★★☆☆☆", content: "If they like you, you'll know. If you are confused, it's a no.", num: "55", color: "Confused Grey", item: "Question Mark" },
    { type: "gentle-reminder", icon: "😅", headline: "Friend Zone", level: "★★☆☆☆", content: "It looks like friendship right now. Don't force romance where it doesn't exist.", num: "99", color: "Friend Orange", item: "High Five" },
    { type: "gentle-reminder", icon: "😅", headline: "Red Flag", level: "★★☆☆☆", content: "That bad feeling you have? Trust it. It is a red flag.", num: "911", color: "Flag Red", item: "Flag" },
    { type: "gentle-reminder", icon: "😅", headline: "Boundaries", level: "★★☆☆☆", content: "Don't say yes just to please them. Set your boundaries clearly.", num: "10", color: "Wall Grey", item: "Fence" },
    { type: "gentle-reminder", icon: "😅", headline: "Wait", level: "★★☆☆☆", content: "The timing is bad. Wait for the storm to pass before bringing up that topic.", num: "30", color: "Rain Blue", item: "Umbrella" },
    { type: "gentle-reminder", icon: "😅", headline: "Delusional", level: "★★☆☆☆", content: "Are you in love with the person, or the idea of them? Be honest.", num: "00", color: "Cloudy White", item: "Bubble" },
    { type: "gentle-reminder", icon: "😅", headline: "Focus on You", level: "★★☆☆☆", content: "Cancel the date. Take yourself out instead. You need 'Me Time'.", num: "80", color: "Solo Gold", item: "Ticket" },
    { type: "gentle-reminder", icon: "😅", headline: "Healing", level: "★★☆☆☆", content: "Your heart is still recovering. Give it time to heal properly.", num: "365", color: "Bandage Beige", item: "Bandage" },
    { type: "gentle-reminder", icon: "😅", headline: "Talk", level: "★★☆☆☆", content: "Communication is key. Don't guess what they are thinking—ask them.", num: "121", color: "Talk Blue", item: "Speech Bubble" },
    { type: "gentle-reminder", icon: "😅", headline: "Guard Heart", level: "★★☆☆☆", content: "Keep your heart guarded for now. Not everyone deserves access.", num: "9", color: "Lock Silver", item: "Shield" },
    { type: "gentle-reminder", icon: "😅", headline: "Too Much", level: "★★☆☆☆", content: "You are giving 110% and they are giving 20%. Pull back.", num: "20", color: "Unfair Grey", item: "Scale" },
    { type: "gentle-reminder", icon: "😅", headline: "Drama Free", level: "★★☆☆☆", content: "Avoid drama at all costs today. Walk away from the argument.", num: "000", color: "Peace White", item: "Earplugs" },
    { type: "shaky-chaos", icon: "🤪", headline: "Pizza Love", level: "⚡⚡⚡", content: "Relationship Status: In a committed relationship with Pizza.", num: "8888", color: "Cheese Yellow", item: "Pizza Slice" },
    { type: "shaky-chaos", icon: "🤪", headline: "Cat Lady", level: "⚡⚡⚡", content: "Shaky predicts you will have 10 cats. They will love you forever.", num: "10", color: "Fur Orange", item: "Cat Food" },
    { type: "shaky-chaos", icon: "🤪", headline: "Error 404", level: "⚡⚡⚡", content: "Love Not Found. Please try updating your personality drivers.", num: "404", color: "Glitch Blue", item: "Dead Heart" },
    { type: "shaky-chaos", icon: "🤪", headline: "Run Away", level: "⚡⚡⚡", content: "It's a trap! Abort mission! Swipe left immediately!", num: "180", color: "Panic Red", item: "Running Shoe" },
    { type: "shaky-chaos", icon: "🤪", headline: "Alien Lover", level: "⚡⚡⚡", content: "Your true love is currently on Mars. Please wait for Elon Musk.", num: "51", color: "Alien Green", item: "UFO" },
    { type: "shaky-chaos", icon: "🤪", headline: "Bed is Bae", level: "⚡⚡⚡", content: "The only thing you should cuddle today is your pillow. It never argues.", num: "247", color: "Sleepy Blue", item: "Pillow" },
    { type: "shaky-chaos", icon: "🤪", headline: "Chocolate", level: "⚡⚡⚡", content: "Who needs a partner when chocolate exists? Chocolate understands.", num: "10000", color: "Choco Brown", item: "Chocolate Bar" },
    { type: "shaky-chaos", icon: "🤪", headline: "System Crash", level: "⚡⚡⚡", content: "Love Radar has overheated. Too much drama detected.", num: "500", color: "Smoke Grey", item: "Fire Extinguisher" },
    { type: "shaky-chaos", icon: "🤪", headline: "Toxic", level: "⚡⚡⚡", content: "Warning: Toxic levels are high. Put on your hazmat suit.", num: "666", color: "Poison Green", item: "Gas Mask" },
    { type: "shaky-chaos", icon: "🤪", headline: "Ask Mom", level: "⚡⚡⚡", content: "Shaky doesn't know. Go ask your mother when you will get married.", num: "1980", color: "Vintage Rose", item: "Apron" },
    { type: "shaky-chaos", icon: "🤪", headline: "Robot Heart", level: "⚡⚡⚡", content: "Beep Boop. Emotions are inefficient. Be a robot today.", num: "1010", color: "Metal Silver", item: "Battery" },
    { type: "shaky-chaos", icon: "🤪", headline: "Taco Date", level: "⚡⚡⚡", content: "Your soulmate is a Taco. It is spicy and hot.", num: "202", color: "Salsa Red", item: "Taco" },
    { type: "shaky-chaos", icon: "🤪", headline: "Forever Alone", level: "⚡⚡⚡", content: "Just kidding. Maybe. But definitely buy a dog just in case.", num: "111", color: "Lonely Blue", item: "Dog Leash" },
    { type: "shaky-chaos", icon: "🤪", headline: "Ghosting", level: "⚡⚡⚡", content: "They didn't text back? Maybe they were abducted by ghosts.", num: "0000", color: "Transparent", item: "Ghost" },
    { type: "shaky-chaos", icon: "🤪", headline: "Wifi Love", level: "⚡⚡⚡", content: "Home is where the Wifi connects automatically. That is true love.", num: "5", color: "Signal Blue", item: "Router" }
];

// ============================================
// 5. LOVE - Your Move (50 組) - Partner
// ============================================
const loveMovePool = [
    { type: "super-lucky", icon: "😎", headline: "Confess Now", level: "★★★★★", content: "Don't wait another second. Tell them exactly how you feel. The result will be magical.", num: "520", color: "Love Red", item: "Heart" },
    { type: "super-lucky", icon: "😎", headline: "Make the Move", level: "★★★★★", content: "Hold their hand, go for the kiss, or ask for the date. Green lights everywhere.", num: "100", color: "Go Green", item: "Traffic Light" },
    { type: "super-lucky", icon: "😎", headline: "The Grand Gesture", level: "★★★★★", content: "Buy the flowers. Book the ticket. Do something big and romantic today.", num: "999", color: "Luxury Gold", item: "Bouquet" },
    { type: "super-lucky", icon: "😎", headline: "Say Yes", level: "★★★★★", content: "Stop playing hard to get. Just say YES with a big smile.", num: "1", color: "Diamond White", item: "Ring" },
    { type: "super-lucky", icon: "😎", headline: "Send It", level: "★★★★★", content: "That risky text you drafted? Send it. It’s going to work.", num: "777", color: "Lucky Blue", item: "Envelope" },
    { type: "good-vibes", icon: "😊", headline: "Text First", level: "★★★★☆", content: "Don't wait for them. Send a simple 'Thinking of you' or a funny meme.", num: "10", color: "Chat Blue", item: "Phone" },
    { type: "good-vibes", icon: "😊", headline: "Smile", level: "★★★★☆", content: "Your best move today is a genuine smile. It’s the ultimate flirt.", num: "3", color: "Sunny Yellow", item: "Lipstick" },
    { type: "good-vibes", icon: "😊", headline: "Coffee Date", level: "★★★★☆", content: "Keep it casual. Ask them to grab a coffee or bubble tea.", num: "2", color: "Latte Brown", item: "Coffee Cup" },
    { type: "good-vibes", icon: "😊", headline: "Eye Contact", level: "★★★★☆", content: "Look them in the eyes for 3 seconds, then look away. It works.", num: "2020", color: "Vision Violet", item: "Glasses" },
    { type: "good-vibes", icon: "😊", headline: "Compliment", level: "★★★★☆", content: "Notice something specific about them and say it out loud.", num: "5", color: "Sweet Pink", item: "Star" },
    { type: "good-vibes", icon: "😊", headline: "Ask a Question", level: "★★★★☆", content: "People love talking about themselves. Ask them an open-ended question.", num: "8", color: "Curious Orange", item: "Question Mark" },
    { type: "good-vibes", icon: "😊", headline: "Like Story", level: "★★★★☆", content: "React to their story with a heart or fire emoji. Simple and effective.", num: "11", color: "Insta Gradient", item: "Heart Icon" },
    { type: "good-vibes", icon: "😊", headline: "Wear Red", level: "★★★★☆", content: "Wear something red today. It increases attraction and confidence.", num: "7", color: "Passion Red", item: "Red Dress" },
    { type: "good-vibes", icon: "😊", headline: "Share Music", level: "★★★★☆", content: "Send them a song. 'This made me think of you.' Classic move.", num: "33", color: "Melody Purple", item: "Headphones" },
    { type: "good-vibes", icon: "😊", headline: "Reply Fast", level: "★★★★☆", content: "Don't play games. Reply immediately to show you are interested.", num: "60", color: "Fast Green", item: "Lightning" },
    { type: "good-vibes", icon: "😊", headline: "Post Selfie", level: "★★★★☆", content: "Post a cute photo of yourself. Let them come to you.", num: "24", color: "Filter Beige", item: "Camera" },
    { type: "good-vibes", icon: "😊", headline: "Inside Joke", level: "★★★★☆", content: "Bring up a funny memory you share. Laughter connects hearts.", num: "88", color: "Funny Yellow", item: "Mask" },
    { type: "good-vibes", icon: "😊", headline: "Small Gift", level: "★★★★☆", content: "Buy them a snack or a small treat. Acts of service speak loudly.", num: "50", color: "Cookie Brown", item: "Candy" },
    { type: "good-vibes", icon: "😊", headline: "Be Yourself", level: "★★★★☆", content: "Drop the act. Authenticity is your most attractive quality today.", num: "101", color: "Pure White", item: "Mirror" },
    { type: "good-vibes", icon: "😊", headline: "Plan B", level: "★★★★☆", content: "If Plan A fails, suggest a fun alternative immediately.", num: "12", color: "Safe Blue", item: "Map" },
    { type: "gentle-reminder", icon: "😅", headline: "Wait 24h", level: "★★☆☆☆", content: "Do not send that text yet. Wait 24 hours and see if you still want to.", num: "240", color: "Pause Grey", item: "Clock" },
    { type: "gentle-reminder", icon: "😅", headline: "Don't Post", level: "★★☆☆☆", content: "Resist the urge to post vague, sad lyrics. It’s not a good look.", num: "403", color: "Hidden Grey", item: "Delete Key" },
    { type: "gentle-reminder", icon: "😅", headline: "Airplane Mode", level: "★★☆☆☆", content: "Put your phone on airplane mode. You are checking it too much.", num: "15", color: "Offline Black", item: "Airplane" },
    { type: "gentle-reminder", icon: "😅", headline: "Play Cool", level: "★★☆☆☆", content: "You are coming on too strong. Dial it back about 20%.", num: "32", color: "Ice Blue", item: "Ice Cube" },
    { type: "gentle-reminder", icon: "😅", headline: "Double Text", level: "★★☆☆☆", content: "They haven't replied? Do NOT send a second text. Step away.", num: "2", color: "Stop Red", item: "Wall" },
    { type: "gentle-reminder", icon: "😅", headline: "Check Grammar", level: "★★☆☆☆", content: "Read your message three times before hitting send. Typos kill the vibe.", num: "123", color: "Ink Black", item: "Pen" },
    { type: "gentle-reminder", icon: "😅", headline: "Silence", level: "★★☆☆☆", content: "Sometimes no response is a response. Accept the silence.", num: "00", color: "Silent White", item: "Zipper" },
    { type: "gentle-reminder", icon: "😅", headline: "No Drunk Text", level: "★★☆☆☆", content: "Give your phone to a friend. You are not allowed to text tonight.", num: "18", color: "Sober Blue", item: "Water" },
    { type: "gentle-reminder", icon: "😅", headline: "Cancel", level: "★★☆☆☆", content: "If you don't feel like going, cancel. Don't force a bad date.", num: "0", color: "Cancel Red", item: "X Button" },
    { type: "gentle-reminder", icon: "😅", headline: "Boundaries", level: "★★☆☆☆", content: "Don't drop everything just because they called. Finish your work first.", num: "99", color: "Brick Red", item: "Shield" },
    { type: "gentle-reminder", icon: "😅", headline: "Love Yourself", level: "★★☆☆☆", content: "Buy flowers for yourself instead. You deserve them more.", num: "111", color: "Self Pink", item: "Mirror" },
    { type: "gentle-reminder", icon: "😅", headline: "Too Fast", level: "★★☆☆☆", content: "Slow down. You are planning the wedding on the first date.", num: "45", color: "Slow Yellow", item: "Snail" },
    { type: "gentle-reminder", icon: "😅", headline: "Think Twice", level: "★★☆☆☆", content: "Is this a good idea? Really? Think one more time.", num: "22", color: "Brain Grey", item: "Brain" },
    { type: "gentle-reminder", icon: "😅", headline: "Low Battery", level: "★★☆☆☆", content: "Your social battery is low. Recharge before you interact.", num: "9", color: "Dim Grey", item: "Battery" },
    { type: "gentle-reminder", icon: "😅", headline: "Friend Zone", level: "★★☆☆☆", content: "High five them. Keep it platonic for now.", num: "55", color: "Friend Orange", item: "Hand" },
    { type: "shaky-chaos", icon: "🤪", headline: "Interpretive Dance", level: "⚡⚡⚡", content: "Express your love through modern dance. No words. Just movement.", num: "5678", color: "Tutu Pink", item: "Tutu" },
    { type: "shaky-chaos", icon: "🤪", headline: "T-Rex Arms", level: "⚡⚡⚡", content: "Walk around with T-Rex arms. If they still like you, it's true love.", num: "65", color: "Dino Green", item: "Dinosaur" },
    { type: "shaky-chaos", icon: "🤪", headline: "Send Meme", level: "⚡⚡⚡", content: "Send the weirdest meme in your phone. Do it now.", num: "69", color: "Clown Red", item: "Clown" },
    { type: "shaky-chaos", icon: "🤪", headline: "Eat Garlic", level: "⚡⚡⚡", content: "Protect yourself from vampires (and bad kisses). Eat raw garlic.", num: "3000", color: "Stinky White", item: "Garlic" },
    { type: "shaky-chaos", icon: "🤪", headline: "Flip Coin", level: "⚡⚡⚡", content: "Heads: Text them. Tails: Move to a new country.", num: "5050", color: "Coin Silver", item: "Coin" },
    { type: "shaky-chaos", icon: "🤪", headline: "Play Dead", level: "⚡⚡⚡", content: "When you see them, pretend to be a fainting goat. Very attractive.", num: "000", color: "Ghost White", item: "Tombstone" },
    { type: "shaky-chaos", icon: "🤪", headline: "Scream", level: "⚡⚡⚡", content: "Go outside and scream their name. (Shaky is not responsible for arrests).", num: "110", color: "Loud Red", item: "Microphone" },
    { type: "shaky-chaos", icon: "🤪", headline: "Wink Fail", level: "⚡⚡⚡", content: "Try to wink, but blink both eyes instead. It's confusingly charming.", num: "222", color: "Blink Blue", item: "Eye" },
    { type: "shaky-chaos", icon: "🤪", headline: "Moonwalk", level: "⚡⚡⚡", content: "Moonwalk away from your problems. And your crush.", num: "1982", color: "Retro Black", item: "Shoe" },
    { type: "shaky-chaos", icon: "🤪", headline: "Robot Mode", level: "⚡⚡⚡", content: "Speak only in binary code. 010101. They will love it.", num: "0101", color: "Metal Grey", item: "Robot" },
    { type: "shaky-chaos", icon: "🤪", headline: "Potato Gift", level: "⚡⚡⚡", content: "Give them a potato. It is a symbol of versatility and starch.", num: "42", color: "Potato Brown", item: "Potato" },
    { type: "shaky-chaos", icon: "🤪", headline: "Aliens", level: "⚡⚡⚡", content: "Tell them you are an alien. If they believe you, marry them.", num: "51", color: "UFO Green", item: "UFO" },
    { type: "shaky-chaos", icon: "🤪", headline: "Ninja Vanish", level: "⚡⚡⚡", content: "Throw a smoke bomb and disappear. Keep the mystery alive.", num: "9999", color: "Smoke Grey", item: "Smoke" },
    { type: "shaky-chaos", icon: "🤪", headline: "Meow", level: "⚡⚡⚡", content: "Answer every question with 'Meow'.", num: "9", color: "Cat Orange", item: "Cat Ear" },
    { type: "shaky-chaos", icon: "🤪", headline: "Banana", level: "⚡⚡⚡", content: "Call them on a banana phone. Ring ring.", num: "1010", color: "Banana Yellow", item: "Banana" }
];

// ============================================
// 6. LOVE - Red Flags (50 組) - Self
// ============================================
const loveSelfPool = [
    { type: "super-lucky", icon: "😎", headline: "Green Flag", level: "★★★★★", content: "No red flags detected. This person is emotionally mature, kind, and safe. A rare find!", num: "100", color: "Safe Green", item: "Checkmark" },
    { type: "super-lucky", icon: "😎", headline: "Golden Soul", level: "★★★★★", content: "They treat waiters nicely and love animals. Basically a Golden Retriever in human form.", num: "1", color: "Pure Gold", item: "Halo" },
    { type: "super-lucky", icon: "😎", headline: "Safe Haven", level: "★★★★★", content: "You feel calm around them, not anxious. That peace is the biggest green flag of all.", num: "0", color: "Calm White", item: "Dove" },
    { type: "super-lucky", icon: "😎", headline: "Clear Intent", level: "★★★★★", content: "No games. No guessing. They tell you exactly what they want (and it's you).", num: "2020", color: "Clear Blue", item: "Crystal" },
    { type: "super-lucky", icon: "😎", headline: "Jackpot", level: "★★★★★", content: "Apologizes when wrong? Communicates clearly? Marry them immediately.", num: "777", color: "Wedding White", item: "Ring" },
    { type: "good-vibes", icon: "😊", headline: "Texts Back", level: "★★★★☆", content: "They reply within a reasonable time. Consistent communication is sexy.", num: "10", color: "Chat Blue", item: "Phone" },
    { type: "good-vibes", icon: "😊", headline: "Good Listener", level: "★★★★☆", content: "They remember that small detail you mentioned three days ago. Green flag.", num: "2", color: "Ear Beige", item: "Note" },
    { type: "good-vibes", icon: "😊", headline: "Respects No", level: "★★★★☆", content: "When you say no, they listen without pushing. This is healthy.", num: "4", color: "Safe Green", item: "Shield" },
    { type: "good-vibes", icon: "😊", headline: "Has Hobbies", level: "★★★★☆", content: "They have a life outside of you. Independence is very attractive.", num: "5", color: "Active Orange", item: "Ball" },
    { type: "good-vibes", icon: "😊", headline: "Nice Friends", level: "★★★★☆", content: "You are the average of the 5 people around you. Their friends are cool, so they are too.", num: "55", color: "Group Yellow", item: "High Five" },
    { type: "good-vibes", icon: "😊", headline: "Open Book", level: "★★★★☆", content: "Nothing to hide. They unlock their phone in front of you comfortably.", num: "1234", color: "Open White", item: "Book" },
    { type: "good-vibes", icon: "😊", headline: "Supports You", level: "★★★★☆", content: "They cheer for your success instead of competing with you.", num: "11", color: "PomPom Pink", item: "Flag" },
    { type: "good-vibes", icon: "😊", headline: "Vulnerable", level: "★★★★☆", content: "They are not afraid to share feelings or cry. Emotional intelligence confirmed.", num: "99", color: "Soft Blue", item: "Tissue" },
    { type: "good-vibes", icon: "😊", headline: "Consistent", level: "★★★★☆", content: "Their words match their actions. No confusion, just clarity.", num: "101", color: "Solid Grey", item: "Rock" },
    { type: "good-vibes", icon: "😊", headline: "Family Vibes", level: "★★★★☆", content: "They talk respectfully about their family (or have valid reasons not to).", num: "8", color: "Home Brown", item: "House" },
    { type: "good-vibes", icon: "😊", headline: "Makes Effort", level: "★★★★☆", content: "They plan dates. They drive to see you. Effort is attractive.", num: "100", color: "Energy Red", item: "Car" },
    { type: "good-vibes", icon: "😊", headline: "Good Exes", level: "★★★★☆", content: "They don't call all their exes 'crazy'. Mature breakups are a good sign.", num: "0", color: "Mature Purple", item: "Handshake" },
    { type: "good-vibes", icon: "😊", headline: "Patience", level: "★★★★☆", content: "They don't get angry in traffic or slow lines. Emotional control is key.", num: "60", color: "Slow Green", item: "Watch" },
    { type: "good-vibes", icon: "😊", headline: "Curious", level: "★★★★☆", content: "They ask questions about your world. They want to know you.", num: "3", color: "Curious Orange", item: "Magnifier" },
    { type: "good-vibes", icon: "😊", headline: "Kindness", level: "★★★★☆", content: "They are kind to animals and strangers. The ultimate green flag.", num: "9", color: "Heart Red", item: "Paw" },
    { type: "gentle-reminder", icon: "😅", headline: "Love Bomb", level: "★★☆☆☆", content: "Too much, too soon? Saying 'I love you' after 2 days is a huge Red Flag.", num: "200", color: "Bomb Red", item: "Bomb" },
    { type: "gentle-reminder", icon: "😅", headline: "Hides Phone", level: "★★☆☆☆", content: "Phone always face down? Takes calls in another room? Suspicious.", num: "404", color: "Secret Black", item: "Lock" },
    { type: "gentle-reminder", icon: "😅", headline: "Rude to Staff", level: "★★☆☆☆", content: "If they are rude to the waiter, they will eventually be rude to you. Run.", num: "0", color: "Rude Red", item: "Plate" },
    { type: "gentle-reminder", icon: "😅", headline: "Self-Centered", level: "★★☆☆☆", content: "Do they ask about you? Or just talk about themselves for 2 hours?", num: "1", color: "Ego Gold", item: "Mirror" },
    { type: "gentle-reminder", icon: "😅", headline: "The Ex", level: "★★☆☆☆", content: "They talk about their ex constantly. They are not over it. Abort mission.", num: "3", color: "Ghost Grey", item: "Ghost" },
    { type: "gentle-reminder", icon: "😅", headline: "Jealousy", level: "★★☆☆☆", content: "Getting angry because you liked a post? Possessiveness is not cute.", num: "99", color: "Envy Green", item: "Chain" },
    { type: "gentle-reminder", icon: "😅", headline: "Gaslighting", level: "★★☆☆☆", content: "'You're crazy', 'That never happened'. If you question your reality, leave.", num: "911", color: "Toxic Green", item: "Gas Mask" },
    { type: "gentle-reminder", icon: "😅", headline: "Hot & Cold", level: "★★☆☆☆", content: "One day they love you, next day they ignore you. Inconsistency is a flag.", num: "5050", color: "Ice Blue", item: "Thermometer" },
    { type: "gentle-reminder", icon: "😅", headline: "No Label", level: "★★☆☆☆", content: "Six months and still 'just having fun'? They will never commit. Move on.", num: "40", color: "Blurry Grey", item: "Label" },
    { type: "gentle-reminder", icon: "😅", headline: "Bad Tipper", level: "★★☆☆☆", content: "They don't tip or they tip poorly. It shows a lack of generosity.", num: "00", color: "Cheap Brown", item: "Coin" },
    { type: "gentle-reminder", icon: "😅", headline: "Victim Mode", level: "★★☆☆☆", content: "Everything is always someone else's fault. They take no responsibility.", num: "15", color: "Sad Blue", item: "Violin" },
    { type: "gentle-reminder", icon: "😅", headline: "Pushy", level: "★★☆☆☆", content: "They pressure you to do things you aren't ready for. Boundaries matter.", num: "10", color: "Pressure Red", item: "Wall" },
    { type: "gentle-reminder", icon: "😅", headline: "Breadcrumbing", level: "★★☆☆☆", content: "Giving you just enough attention to keep you, but never enough to satisfy you.", num: "5", color: "Crumb Brown", item: "Bread" },
    { type: "gentle-reminder", icon: "😅", headline: "Flirty", level: "★★☆☆☆", content: "They flirt with everyone in front of you. That's disrespect, not charm.", num: "69", color: "Cheating Red", item: "Wink" },
    { type: "gentle-reminder", icon: "😅", headline: "No Friends", level: "★★☆☆☆", content: "They have zero long-term friends. Why? Are they the problem?", num: "0", color: "Lonely Grey", item: "Island" },
    { type: "shaky-chaos", icon: "🤪", headline: "Pineapple Pizza", level: "⚡⚡⚡", content: "They put pineapple on pizza. Is this a culinary crime or true love?", num: "888", color: "Pineapple Yellow", item: "Pizza" },
    { type: "shaky-chaos", icon: "🤪", headline: "Socks & Sandals", level: "⚡⚡⚡", content: "Fashion police alert! They wear socks with sandals. Proceed with caution.", num: "2", color: "Ugly Brown", item: "Sandal" },
    { type: "shaky-chaos", icon: "🤪", headline: "Claps on Plane", level: "⚡⚡⚡", content: "They clap when the airplane lands. Huge Red Flag. Or maybe just happy?", num: "747", color: "Loud White", item: "Plane" },
    { type: "shaky-chaos", icon: "🤪", headline: "Chews Loudly", level: "⚡⚡⚡", content: "Smack. Smack. Smack. If you have misophonia, this relationship is doomed.", num: "110", color: "Noise Red", item: "Mouth" },
    { type: "shaky-chaos", icon: "🤪", headline: "Milk Before Cereal", level: "⚡⚡⚡", content: "They pour milk before the cereal. This person is a psychopath.", num: "321", color: "Milk White", item: "Bowl" },
    { type: "shaky-chaos", icon: "🤪", headline: "Text Bubble", level: "⚡⚡⚡", content: "Their texts are Green (Android) and you are Blue (iPhone). Can it work?", num: "505", color: "Bubble Green", item: "Robot" },
    { type: "shaky-chaos", icon: "🤪", headline: "Hates Tacos", level: "⚡⚡⚡", content: "Who hates tacos? Suspicious. Very suspicious.", num: "403", color: "No Salsa Red", item: "Taco" },
    { type: "shaky-chaos", icon: "🤪", headline: "Vampire?", level: "⚡⚡⚡", content: "They never go out in the sun and hate garlic. Possible vampire.", num: "1800", color: "Blood Red", item: "Cape" },
    { type: "shaky-chaos", icon: "🤪", headline: "Three Owls", level: "⚡⚡⚡", content: "Red Flag: They might actually be three owls in a trench coat.", num: "3", color: "Feather Brown", item: "Coat" },
    { type: "shaky-chaos", icon: "🤪", headline: "Flat Earther", level: "⚡⚡⚡", content: "They think the earth is flat. If you date them, don't walk too far.", num: "000", color: "Flat Blue", item: "Map" },
    { type: "shaky-chaos", icon: "🤪", headline: "Unicorn", level: "⚡⚡⚡", content: "They are too perfect. They might be a mythical creature. Poke them to check.", num: "1000", color: "Rainbow", item: "Horn" },
    { type: "shaky-chaos", icon: "🤪", headline: "Zodiac Hater", level: "⚡⚡⚡", content: "They hate astrology. Don't tell them you are reading this.", num: "12", color: "Star Grey", item: "Gemini" },
    { type: "shaky-chaos", icon: "🤪", headline: "Ketchup on Eggs", level: "⚡⚡⚡", content: "They put ketchup on everything. Even eggs. Even... you?", num: "57", color: "Sauce Red", item: "Bottle" },
    { type: "shaky-chaos", icon: "🤪", headline: "One Sock", level: "⚡⚡⚡", content: "They wear only one sock. Chaos energy is too high.", num: "1", color: "Sock Blue", item: "Sock" },
    { type: "shaky-chaos", icon: "🤪", headline: "Toilet Paper", level: "⚡⚡⚡", content: "They put the toilet paper roll under, not over. Unforgivable.", num: "2", color: "Paper White", item: "Roll" }
];

// ============================================
// 7. CAREER - Money Bag (50 組) - Job
// ============================================
const careerMoneyPool = [
    { type: "super-lucky", icon: "😎", headline: "Money Rain", level: "★★★★★", content: "It's raining money! A bonus, a raise, or a winning lottery ticket is coming.", num: "8888", color: "Rich Gold", item: "Money Bag" },
    { type: "super-lucky", icon: "😎", headline: "Big Deal", level: "★★★★★", content: "You will close that deal or sell that item for a high price. Profit is yours.", num: "10000", color: "Profit Green", item: "Handshake" },
    { type: "super-lucky", icon: "😎", headline: "Debt Free", level: "★★★★★", content: "A financial burden will be lifted. You are moving towards total freedom.", num: "0", color: "Freedom White", item: "Wing" },
    { type: "super-lucky", icon: "😎", headline: "Investment Win", level: "★★★★★", content: "Your assets are growing. Green arrows everywhere. Check your portfolio.", num: "777", color: "Stock Green", item: "Chart" },
    { type: "super-lucky", icon: "😎", headline: "Top Tier", level: "★★★★★", content: "You are attracting high-value opportunities. Don't settle for cheap.", num: "1", color: "Platinum", item: "Diamond" },
    { type: "good-vibes", icon: "😊", headline: "Discount", level: "★★★★☆", content: "You will find exactly what you need at a 50% discount. Smart shopper!", num: "50", color: "Sale Red", item: "Tag" },
    { type: "good-vibes", icon: "😊", headline: "Free Lunch", level: "★★★★☆", content: "Someone will treat you to a meal or coffee today. Say thank you!", num: "0", color: "Yummy Yellow", item: "Burger" },
    { type: "good-vibes", icon: "😊", headline: "Found Money", level: "★★★★☆", content: "Check your old coat pockets. There is cash waiting for you.", num: "100", color: "Cash Green", item: "Coin" },
    { type: "good-vibes", icon: "😊", headline: "Side Hustle", level: "★★★★☆", content: "A small idea could bring in extra cash. Start that project now.", num: "5", color: "Hustle Blue", item: "Laptop" },
    { type: "good-vibes", icon: "😊", headline: "Under Budget", level: "★★★★☆", content: "You will spend less than you planned. Pat yourself on the back.", num: "20", color: "Budget Blue", item: "Calculator" },
    { type: "good-vibes", icon: "😊", headline: "Cashback", level: "★★★★☆", content: "Points, miles, or cashback are adding up. It's like free money.", num: "10", color: "Credit Silver", item: "Card" },
    { type: "good-vibes", icon: "😊", headline: "Gift Incoming", level: "★★★★☆", content: "You won't have to buy it—someone is going to give it to you.", num: "25", color: "Gift Pink", item: "Ribbon" },
    { type: "good-vibes", icon: "😊", headline: "Negotiation", level: "★★★★☆", content: "Ask for a lower price. Today, they will say yes.", num: "99", color: "Deal Orange", item: "Gavel" },
    { type: "good-vibes", icon: "😊", headline: "Extra Shift", level: "★★★★☆", content: "An opportunity to work a little more for extra pay is coming.", num: "15", color: "Work Grey", item: "Clock" },
    { type: "good-vibes", icon: "😊", headline: "Lucky Draw", level: "★★★★☆", content: "Enter that giveaway. Your chances are higher than usual.", num: "66", color: "Lucky Purple", item: "Ticket" },
    { type: "good-vibes", icon: "😊", headline: "Client Love", level: "★★★★☆", content: "A customer or boss loves your work and might pay you early.", num: "11", color: "Happy Yellow", item: "Smile" },
    { type: "good-vibes", icon: "😊", headline: "Full Jar", level: "★★★★☆", content: "Time to count your piggy bank. You have more change than you think.", num: "4", color: "Piggy Pink", item: "Pig" },
    { type: "good-vibes", icon: "😊", headline: "No Fees", level: "★★★★☆", content: "You will avoid a parking ticket or a late fee just in time.", num: "12", color: "Safe Green", item: "Shield" },
    { type: "good-vibes", icon: "😊", headline: "Small Win", level: "★★★★☆", content: "A scratch-off ticket or a small bet will pay for your lunch.", num: "7", color: "Winner Gold", item: "Coin" },
    { type: "good-vibes", icon: "😊", headline: "Utility Bill", level: "★★★★☆", content: "Your electricity or water bill will be lower than expected.", num: "6", color: "Eco Green", item: "Bulb" },
    { type: "gentle-reminder", icon: "😅", headline: "Stop Spending", level: "★★☆☆☆", content: "Step away from the 'Buy Now' button. You do not need it.", num: "403", color: "Stop Red", item: "Hand" },
    { type: "gentle-reminder", icon: "😅", headline: "Subscription", level: "★★☆☆☆", content: "Check your subscriptions. You are paying for something you don't use.", num: "30", color: "Monthly Grey", item: "Calendar" },
    { type: "gentle-reminder", icon: "😅", headline: "Cook Home", level: "★★☆☆☆", content: "Delivery fees are eating your wallet. Cook pasta at home tonight.", num: "15", color: "Kitchen White", item: "Fork" },
    { type: "gentle-reminder", icon: "😅", headline: "30 Day Rule", level: "★★☆☆☆", content: "Wait 30 days before buying that big item. If you still want it, then buy.", num: "30", color: "Wait Yellow", item: "Hourglass" },
    { type: "gentle-reminder", icon: "😅", headline: "Impulse Buy", level: "★★☆☆☆", content: "You are emotional right now. Emotional spending leads to regret.", num: "24", color: "Regret Blue", item: "Tear" },
    { type: "gentle-reminder", icon: "😅", headline: "Hidden Fees", level: "★★☆☆☆", content: "Read the fine print. There is a hidden cost you are missing.", num: "9", color: "Sneaky Black", item: "Magnifier" },
    { type: "gentle-reminder", icon: "😅", headline: "Emergency Fund", level: "★★☆☆☆", content: "Don't spend your savings. You might need it for a rainy day soon.", num: "911", color: "Safe Orange", item: "Umbrella" },
    { type: "gentle-reminder", icon: "😅", headline: "Scam Alert", level: "★★☆☆☆", content: "If it sounds too good to be true, it is. Keep your wallet closed.", num: "404", color: "Warning Red", item: "Mask" },
    { type: "gentle-reminder", icon: "😅", headline: "Pay Bills", level: "★★☆☆☆", content: "Did you forget a bill? Check your due dates to avoid interest.", num: "31", color: "Deadline Red", item: "Calendar" },
    { type: "gentle-reminder", icon: "😅", headline: "Coffee Adds Up", level: "★★☆☆☆", content: "Your daily coffee habit is costing you a vacation. Make it yourself.", num: "5", color: "Coffee Brown", item: "Cup" },
    { type: "gentle-reminder", icon: "😅", headline: "Quality First", level: "★★☆☆☆", content: "Don't buy cheap junk. It breaks fast. Buy one good thing instead.", num: "1", color: "Quality Gold", item: "Diamond" },
    { type: "gentle-reminder", icon: "😅", headline: "No Lending", level: "★★☆☆☆", content: "Do not lend money to friends today. You won't see it back.", num: "00", color: "Empty White", item: "Pocket" },
    { type: "gentle-reminder", icon: "😅", headline: "Compare Price", level: "★★☆☆☆", content: "Don't buy the first one you see. It's cheaper on another website.", num: "2", color: "Search Blue", item: "Phone" },
    { type: "gentle-reminder", icon: "😅", headline: "Bring Lunch", level: "★★☆☆☆", content: "Pack your lunch tomorrow. Your bank account will thank you.", num: "12", color: "Sandwich Beige", item: "Box" },
    { type: "gentle-reminder", icon: "😅", headline: "Free Trial", level: "★★☆☆☆", content: "Cancel that free trial before they charge you automatically.", num: "7", color: "Trap Grey", item: "Mouse Trap" },
    { type: "shaky-chaos", icon: "🤪", headline: "Crypto King", level: "⚡⚡⚡", content: "Invest everything in Dogecoin. (Disclaimer: Shaky is not a financial advisor).", num: "420", color: "Doge Yellow", item: "Dog" },
    { type: "shaky-chaos", icon: "🤪", headline: "Sell Kidney", level: "⚡⚡⚡", content: "You have two kidneys, but you only need one... Just kidding. Drink water.", num: "2", color: "Organ Pink", item: "Ice" },
    { type: "shaky-chaos", icon: "🤪", headline: "Marry Rich", level: "⚡⚡⚡", content: "Stop working. Find a rich partner. Problem solved.", num: "1000000", color: "Diamond Blue", item: "Ring" },
    { type: "shaky-chaos", icon: "🤪", headline: "Couch Mining", level: "⚡⚡⚡", content: "Dig into your sofa. There is a fortune in lost coins waiting.", num: "55", color: "Dust Grey", item: "Sofa" },
    { type: "shaky-chaos", icon: "🤪", headline: "Dirt Diet", level: "⚡⚡⚡", content: "Ran out of money? Dirt is free. It tastes like nature.", num: "0", color: "Dirt Brown", item: "Spoon" },
    { type: "shaky-chaos", icon: "🤪", headline: "Monopoly", level: "⚡⚡⚡", content: "Use Monopoly money to pay for lunch. See if they notice.", num: "500", color: "Fake Orange", item: "Toy Cash" },
    { type: "shaky-chaos", icon: "🤪", headline: "Sugar Daddy", level: "⚡⚡⚡", content: "Shaky predicts a Sugar Daddy/Mommy in your future. Start stretching.", num: "69", color: "Sugar White", item: "Candy" },
    { type: "shaky-chaos", icon: "🤪", headline: "NFT", level: "⚡⚡⚡", content: "Buy a picture of a bored monkey. It will be worth $0 soon.", num: "000", color: "Pixel Art", item: "Monkey" },
    { type: "shaky-chaos", icon: "🤪", headline: "Pirate Life", level: "⚡⚡⚡", content: "Quit your job. Buy a boat. Find buried treasure.", num: "X", color: "Map Yellow", item: "Skull" },
    { type: "shaky-chaos", icon: "🤪", headline: "Money Tree", level: "⚡⚡⚡", content: "Plant a dollar bill in the garden. Water it daily. Good luck.", num: "1", color: "Plant Green", item: "Leaf" },
    { type: "shaky-chaos", icon: "🤪", headline: "Instant Noodles", level: "⚡⚡⚡", content: "Prepare your stomach. You will be eating instant noodles for a week.", num: "3", color: "Soup Yellow", item: "Noodles" },
    { type: "shaky-chaos", icon: "🤪", headline: "Bank Error", level: "⚡⚡⚡", content: "Monopoly card: Bank error in your favor. Collect $200.", num: "200", color: "Card Yellow", item: "Card" },
    { type: "shaky-chaos", icon: "🤪", headline: "Sell Feet Pics", level: "⚡⚡⚡", content: "Desperate times call for desperate measures. How cute are your toes?", num: "10", color: "Skin Beige", item: "Foot" },
    { type: "shaky-chaos", icon: "🤪", headline: "Tooth Fairy", level: "⚡⚡⚡", content: "Pull out a tooth. Put it under your pillow. Profit.", num: "32", color: "Bone White", item: "Tooth" },
    { type: "shaky-chaos", icon: "🤪", headline: "Rich Relative", level: "⚡⚡⚡", content: "Wait for a call from a long-lost uncle who is a prince. Any minute now...", num: "9999", color: "Royal Purple", item: "Crown" }
];

// ============================================
// 8. CAREER - Boss Battle (50 組) - Wealth (Should be Boss)
// ============================================
const careerBossPool = [
    { type: "super-lucky", icon: "😎", headline: "Level Up", level: "★★★★★", content: "Promotion unlocked! You have defeated the current level. New title and salary acquired.", num: "1", color: "Gold Medal", item: "Trophy" },
    { type: "super-lucky", icon: "😎", headline: "Boss Away", level: "★★★★★", content: "The Boss is on vacation or sick leave. The office is yours. Enjoy the freedom.", num: "0", color: "Freedom Blue", item: "Empty Chair" },
    { type: "super-lucky", icon: "😎", headline: "Big Bonus", level: "★★★★★", content: "Unexpected loot drop! A bonus or commission is hitting your bank account.", num: "10000", color: "Rich Green", item: "Money Bag" },
    { type: "super-lucky", icon: "😎", headline: "Perfect Pitch", level: "★★★★★", content: "Your presentation was flawless. The Boss is stunned. Standing ovation.", num: "100", color: "Star Yellow", item: "Mic" },
    { type: "super-lucky", icon: "😎", headline: "Headhunted", level: "★★★★★", content: "A better company wants you. You hold all the cards now. Negotiate hard.", num: "2", color: "Power Red", item: "Offer Letter" },
    { type: "good-vibes", icon: "😊", headline: "Leave Approved", level: "★★★★☆", content: "Your vacation request is approved instantly. No questions asked. Book the flight.", num: "365", color: "Holiday Blue", item: "Plane" },
    { type: "good-vibes", icon: "😊", headline: "Early Finish", level: "★★★★☆", content: "The Boss says 'Go home early today'. Do not hesitate. Run.", num: "1700", color: "Sunset Orange", item: "Clock" },
    { type: "good-vibes", icon: "😊", headline: "Free Coffee", level: "★★★★☆", content: "The Boss is buying coffee for everyone. Order the most expensive latte.", num: "5", color: "Latte Brown", item: "Cup" },
    { type: "good-vibes", icon: "😊", headline: "Good Mood", level: "★★★★☆", content: "The Boss is in a surprisingly good mood today. Safe to approach.", num: "10", color: "Safe Green", item: "Smiley" },
    { type: "good-vibes", icon: "😊", headline: "Meeting Cancelled", level: "★★★★☆", content: "That 2-hour useless meeting? Cancelled. You just gained 2 hours of life.", num: "2", color: "Relief White", item: "Calendar" },
    { type: "good-vibes", icon: "😊", headline: "Public Praise", level: "★★★★☆", content: "You got a shout-out in the group chat or meeting. Reputation +10.", num: "10", color: "Reputation Gold", item: "Thumb Up" },
    { type: "good-vibes", icon: "😊", headline: "Casual Friday", level: "★★★★☆", content: "Wear jeans. Relax. The vibe today is chill and productive.", num: "6", color: "Denim Blue", item: "Jeans" },
    { type: "good-vibes", icon: "😊", headline: "Idea Accepted", level: "★★★★☆", content: "They actually listened to your suggestion. And they liked it.", num: "101", color: "Idea Yellow", item: "Lightbulb" },
    { type: "good-vibes", icon: "😊", headline: "Helpful Feedback", level: "★★★★☆", content: "Instead of criticism, you got constructive advice that actually helps.", num: "1", color: "Growth Green", item: "Ladder" },
    { type: "good-vibes", icon: "😊", headline: "No Emails", level: "★★★★☆", content: "Your inbox is strangely quiet. Enjoy the peace while it lasts.", num: "0", color: "Silent Grey", item: "Envelope" },
    { type: "good-vibes", icon: "😊", headline: "Team Lunch", level: "★★★★☆", content: "Free food on the company card. Order the appetizer and dessert.", num: "12", color: "Yummy Red", item: "Fork" },
    { type: "good-vibes", icon: "😊", headline: "Deadline Extended", level: "★★★★☆", content: "You got more time to finish the project. Breathe.", num: "24", color: "Time Blue", item: "Hourglass" },
    { type: "good-vibes", icon: "😊", headline: "Right Answer", level: "★★★★☆", content: "The Boss asked a tough question, and you nailed the answer.", num: "100", color: "Smart Purple", item: "Brain" },
    { type: "good-vibes", icon: "😊", headline: "Smooth Commute", level: "★★★★☆", content: "Traffic was light, the train was on time. You arrived fresh.", num: "800", color: "Fast Green", item: "Train" },
    { type: "good-vibes", icon: "😊", headline: "Work Bestie", level: "★★★★☆", content: "You and your favorite coworker have time to gossip today. Therapy.", num: "22", color: "Friend Pink", item: "Tea" },
    { type: "gentle-reminder", icon: "😅", headline: "Paper Trail", level: "★★☆☆☆", content: "Don't trust verbal promises. Send an email to confirm. Cover your back.", num: "99", color: "Paper White", item: "Document" },
    { type: "gentle-reminder", icon: "😅", headline: "Be On Time", level: "★★☆☆☆", content: "The Boss is watching the clock today. Do not be late.", num: "900", color: "Alert Red", item: "Watch" },
    { type: "gentle-reminder", icon: "😅", headline: "Look Busy", level: "★★☆☆☆", content: "Even if you have nothing to do, type furiously. Perception is reality.", num: "101", color: "Keyboard Grey", item: "Keyboard" },
    { type: "gentle-reminder", icon: "😅", headline: "Silence Phone", level: "★★☆☆☆", content: "If your phone rings in the meeting, you are dead. Mute it now.", num: "0", color: "Mute Black", item: "Speaker" },
    { type: "gentle-reminder", icon: "😅", headline: "Don't Gossip", level: "★★☆☆☆", content: "Walls have ears. Keep your complaints to yourself today.", num: "3", color: "Secret Purple", item: "Zipper" },
    { type: "gentle-reminder", icon: "😅", headline: "Save File", level: "★★☆☆☆", content: "Ctrl+S right now. Imagine losing 4 hours of work. Do it.", num: "404", color: "Safety Blue", item: "Disk" },
    { type: "gentle-reminder", icon: "😅", headline: "Read Email", level: "★★☆☆☆", content: "Read the whole email before replying. Don't ask questions that are already answered.", num: "1", color: "Detail Orange", item: "Glasses" },
    { type: "gentle-reminder", icon: "😅", headline: "Dress Code", level: "★★☆☆☆", content: "Check your shirt for stains. Appearance matters in the Boss Battle.", num: "7", color: "Clean White", item: "Tie" },
    { type: "gentle-reminder", icon: "😅", headline: "No Reply All", level: "★★☆☆☆", content: "Be careful with the 'Reply All' button. It causes disasters.", num: "500", color: "Danger Red", item: "Button" },
    { type: "gentle-reminder", icon: "😅", headline: "Stay Calm", level: "★★☆☆☆", content: "The Boss might be stressed. Don't take it personally. Be a duck (calm on surface).", num: "10", color: "Duck Yellow", item: "Duck" },
    { type: "gentle-reminder", icon: "😅", headline: "Update Resume", level: "★★☆☆☆", content: "Just in case. It's always good to have an exit strategy ready.", num: "2026", color: "Future Grey", item: "CV" },
    { type: "gentle-reminder", icon: "😅", headline: "Take Notes", level: "★★☆☆☆", content: "Bring a notebook. Writing things down makes you look smarter.", num: "2", color: "Ink Blue", item: "Pen" },
    { type: "gentle-reminder", icon: "😅", headline: "Hide Screen", level: "★★☆☆☆", content: "Close your social media tabs. The Boss is walking behind you.", num: "55", color: "Privacy Black", item: "Screen" },
    { type: "gentle-reminder", icon: "😅", headline: "Coffee First", level: "★★☆☆☆", content: "Do not speak to anyone until you have had caffeine. Safety warning.", num: "8", color: "Coffee Brown", item: "Bean" },
    { type: "gentle-reminder", icon: "😅", headline: "Fake Smile", level: "★★☆☆☆", content: "Just smile and nod. Smile and nod. Get through the day.", num: "11", color: "Mask Beige", item: "Mask" },
    { type: "shaky-chaos", icon: "🤪", headline: "Flip Table", level: "⚡⚡⚡", content: "Rage Quit. Flip the table. Walk out. (Please don't actually do this).", num: "180", color: "Rage Red", item: "Table" },
    { type: "shaky-chaos", icon: "🤪", headline: "T-Pose", level: "⚡⚡⚡", content: "Assert dominance. Stand on your desk and T-Pose at the Boss.", num: "1000", color: "Dominant Gold", item: "T-Shape" },
    { type: "shaky-chaos", icon: "🤪", headline: "Hide", level: "⚡⚡⚡", content: "Crawl under your desk. Build a fort. Live there now.", num: "007", color: "Shadow Grey", item: "Box" },
    { type: "shaky-chaos", icon: "🤪", headline: "Blame Shaky", level: "⚡⚡⚡", content: "If something goes wrong, just say 'Shaky made me do it'.", num: "666", color: "Evil Purple", item: "Finger Point" },
    { type: "shaky-chaos", icon: "🤪", headline: "Toilet Nap", level: "⚡⚡⚡", content: "The safest place is the bathroom stall. Enjoy your 20-minute nap.", num: "20", color: "Tile White", item: "Toilet" },
    { type: "shaky-chaos", icon: "🤪", headline: "Interpretive Dance", level: "⚡⚡⚡", content: "Answer the Boss's question with an interpretive dance routine.", num: "5678", color: "Dance Pink", item: "Shoes" },
    { type: "shaky-chaos", icon: "🤪", headline: "Meme Reply", level: "⚡⚡⚡", content: "Reply to that serious email with a GIF of a cat falling over.", num: "69", color: "Gif Blue", item: "Cat" },
    { type: "shaky-chaos", icon: "🤪", headline: "Become Boss", level: "⚡⚡⚡", content: "Wear a fake mustache. Sit in the Boss's chair. You are the captain now.", num: "1", color: "Fake Black", item: "Mustache" },
    { type: "shaky-chaos", icon: "🤪", headline: "Invisible", level: "⚡⚡⚡", content: "If you don't move, they can't see you. Stay very, very still.", num: "000", color: "Ghost White", item: "Chameleon" },
    { type: "shaky-chaos", icon: "🤪", headline: "Cry", level: "⚡⚡⚡", content: "Crying in the printer room is a valid meeting agenda.", num: "555", color: "Tear Blue", item: "Tissue" },
    { type: "shaky-chaos", icon: "🤪", headline: "Fake Call", level: "⚡⚡⚡", content: "Pretend your grandma is on fire. Run away from the conversation.", num: "911", color: "Emergency Red", item: "Phone" },
    { type: "shaky-chaos", icon: "🤪", headline: "Pajamas", level: "⚡⚡⚡", content: "Show up in pajamas. Tell them it's 'High Fashion'.", num: "24", color: "Sleepy Blue", item: "Pillow" },
    { type: "shaky-chaos", icon: "🤪", headline: "Alien", level: "⚡⚡⚡", content: "Your Boss is an alien wearing a human suit. Shaky knows.", num: "51", color: "Alien Green", item: "UFO" },
    { type: "shaky-chaos", icon: "🤪", headline: "Dinosaur", level: "⚡⚡⚡", content: "Roar at the printer. It knows what it did.", num: "65", color: "Dino Green", item: "Printer" },
    { type: "shaky-chaos", icon: "🤪", headline: "Lottery", level: "⚡⚡⚡", content: "Check your ticket. Maybe you don't need this job anymore.", num: "77777", color: "Dream Gold", item: "Ticket" }
];

// ============================================
// 9. CAREER - Office Tea (50 組) - Goal
// ============================================
const careerGoalPool = [
    { type: "super-lucky", icon: "😎", headline: "Office Favorite", level: "★★★★★", content: "Everyone is talking about you, and it's all good things. You are the MVP.", num: "1", color: "Star Gold", item: "Crown" },
    { type: "super-lucky", icon: "😎", headline: "Teflon", level: "★★★★★", content: "The drama is flying everywhere, but none of it sticks to you. You are safe.", num: "0", color: "Shield Silver", item: "Shield" },
    { type: "super-lucky", icon: "😎", headline: "Insider Info", level: "★★★★★", content: "You know the big news before the official email comes out. Knowledge is power.", num: "100", color: "Key Gold", item: "Key" },
    { type: "super-lucky", icon: "😎", headline: "Secret Ally", level: "★★★★★", content: "A powerful person in the office is secretly on your side. They have your back.", num: "7", color: "Shadow Blue", item: "Handshake" },
    { type: "super-lucky", icon: "😎", headline: "Vindication", level: "★★★★★", content: "You were right all along. Today, everyone realizes it and apologizes.", num: "10", color: "Truth White", item: "Gavel" },
    { type: "good-vibes", icon: "😊", headline: "Spill the Tea", level: "★★★★☆", content: "Get your popcorn ready. The gossip today is juicy, entertaining, and harmless.", num: "88", color: "Tea Brown", item: "Teapot" },
    { type: "good-vibes", icon: "😊", headline: "Lunch Crew", level: "★★★★☆", content: "A spontaneous team lunch will happen. It will be full of laughter.", num: "12", color: "Burger Orange", item: "Burger" },
    { type: "good-vibes", icon: "😊", headline: "Shared Look", level: "★★★★☆", content: "That moment when you and a coworker make eye contact and know exactly what the other is thinking.", num: "2020", color: "Eye Blue", item: "Glasses" },
    { type: "good-vibes", icon: "😊", headline: "Free Snacks", level: "★★★★☆", content: "There is leftover cake or donuts in the breakroom. Go now!", num: "30", color: "Donut Pink", item: "Donut" },
    { type: "good-vibes", icon: "😊", headline: "Work Bestie", level: "★★★★☆", content: "Your work bestie will save your sanity today. Send them a thank you meme.", num: "2", color: "Friend Yellow", item: "Heart" },
    { type: "good-vibes", icon: "😊", headline: "New Hire", level: "★★★★☆", content: "The new person is actually really cool and might become a friend.", num: "11", color: "Fresh Green", item: "Plant" },
    { type: "good-vibes", icon: "😊", headline: "Funny Meme", level: "★★★★☆", content: "The group chat is on fire today. The memes are top tier.", num: "69", color: "Meme Blue", item: "Phone" },
    { type: "good-vibes", icon: "😊", headline: "Compliment", level: "★★★★☆", content: "You will overhear someone saying something nice about your work.", num: "5", color: "Blush Pink", item: "Ear" },
    { type: "good-vibes", icon: "😊", headline: "Office Crush", level: "★★★★☆", content: "Your office crush (or eye candy) will talk to you today. Play it cool.", num: "520", color: "Love Red", item: "Candy" },
    { type: "good-vibes", icon: "😊", headline: "Happy Hour", level: "★★★★☆", content: "Drinks after work? Yes. It will be worth the hangover.", num: "17", color: "Beer Gold", item: "Glass" },
    { type: "good-vibes", icon: "😊", headline: "Secret Stash", level: "★★★★☆", content: "You will find a forgotten snack in your drawer. It is a gift from past you.", num: "3", color: "Choco Brown", item: "Cookie" },
    { type: "good-vibes", icon: "😊", headline: "Office Pet", level: "★★★★☆", content: "Someone brought a dog/cat to the office (or a zoom call). Mood boosted.", num: "4", color: "Fur Brown", item: "Paw" },
    { type: "good-vibes", icon: "😊", headline: "Common Enemy", level: "★★★★☆", content: "Nothing bonds a team like complaining about the same annoying thing.", num: "99", color: "Bonding Grey", item: "Chain" },
    { type: "good-vibes", icon: "😊", headline: "Music Vibe", level: "★★★★☆", content: "Whoever is controlling the office playlist is nailing it today.", num: "33", color: "Music Purple", item: "Note" },
    { type: "good-vibes", icon: "😊", headline: "Good Gossip", level: "★★★★☆", content: "You hear that someone annoying is leaving. Ding dong!", num: "888", color: "Bye White", item: "Door" },
    { type: "gentle-reminder", icon: "😅", headline: "Zip It", level: "★★☆☆☆", content: "Do not say that out loud. Walls have ears. Keep it in your head.", num: "00", color: "Silent Black", item: "Zipper" },
    { type: "gentle-reminder", icon: "😅", headline: "HR Alert", level: "★★☆☆☆", content: "Remember, HR is not your friend. Be careful what you report.", num: "911", color: "Warning Red", item: "File" },
    { type: "gentle-reminder", icon: "😅", headline: "Screenshot", level: "★★☆☆☆", content: "Do not screenshot that chat. It can be traced. Risky move.", num: "404", color: "Trace Grey", item: "Camera" },
    { type: "gentle-reminder", icon: "😅", headline: "Wrong Chat", level: "★★☆☆☆", content: "Check who you are sending that message to. Don't send the complaint to the Boss.", num: "500", color: "Panic Red", item: "Message" },
    { type: "gentle-reminder", icon: "😅", headline: "Fake Friend", level: "★★☆☆☆", content: "There is a snake in the grass. Not everyone smiling at you is your friend.", num: "66", color: "Snake Green", item: "Snake" },
    { type: "gentle-reminder", icon: "😅", headline: "Headphones On", level: "★★☆☆☆", content: "Put your headphones on. Do not get involved in the drama happening behind you.", num: "101", color: "Block White", item: "Headphones" },
    { type: "gentle-reminder", icon: "😅", headline: "Stay Neutral", level: "★★☆☆☆", content: "Office politics are heating up. Be Switzerland. Take no sides.", num: "5050", color: "Neutral Grey", item: "Flag" },
    { type: "gentle-reminder", icon: "😅", headline: "Bathroom Talk", level: "★★☆☆☆", content: "Check the stalls before you start gossiping in the bathroom.", num: "6", color: "Tile White", item: "Toilet Paper" },
    { type: "gentle-reminder", icon: "😅", headline: "TMI", level: "★★☆☆☆", content: "Too Much Information. Your coworkers don't need to know about your rash.", num: "9", color: "Awkward Pink", item: "Bandage" },
    { type: "gentle-reminder", icon: "😅", headline: "The Spy", level: "★★☆☆☆", content: "Someone is reporting everything back to the boss. Watch your back.", num: "007", color: "Spy Black", item: "Glasses" },
    { type: "gentle-reminder", icon: "😅", headline: "Vent Outside", level: "★★☆☆☆", content: "Need to complain? Call a non-work friend. Do not do it in the office.", num: "18", color: "Safe Blue", item: "Phone" },
    { type: "gentle-reminder", icon: "😅", headline: "Slack History", level: "★★☆☆☆", content: "Your company can read your DMs. Act accordingly.", num: "2026", color: "Digital Blue", item: "Eye" },
    { type: "gentle-reminder", icon: "😅", headline: "Not Your Circus", level: "★★☆☆☆", content: "Not your circus, not your monkeys. Stay out of the mess.", num: "110", color: "Circus Red", item: "Tent" },
    { type: "gentle-reminder", icon: "😅", headline: "Don't Spread It", level: "★★☆☆☆", content: "The rumor you heard is false. Stop the chain.", num: "15", color: "Stop Red", item: "Hand" },
    { type: "gentle-reminder", icon: "😅", headline: "Clean Up", level: "★★☆☆☆", content: "Don't be the person who leaves a dirty dish in the sink. People talk.", num: "8", color: "Soap Blue", item: "Sponge" },
    { type: "shaky-chaos", icon: "🤪", headline: "Fridge Thief", level: "⚡⚡⚡", content: "Someone ate your sandwich. Trust no one. It was probably 'Kevin'.", num: "403", color: "Hungry Yellow", item: "Sandwich" },
    { type: "shaky-chaos", icon: "🤪", headline: "Ghost", level: "⚡⚡⚡", content: "The office is haunted by an employee who never clocked out.", num: "666", color: "Ghost White", item: "Ghost" },
    { type: "shaky-chaos", icon: "🤪", headline: "Alien Boss", level: "⚡⚡⚡", content: "Rumor has it the CEO is actually three lizards in a suit.", num: "51", color: "Lizard Green", item: "UFO" },
    { type: "shaky-chaos", icon: "🤪", headline: "Fish Guy", level: "⚡⚡⚡", content: "Who microwaved fish? The whole floor smells like the ocean. Chaos.", num: "300", color: "Stinky Green", item: "Fish" },
    { type: "shaky-chaos", icon: "🤪", headline: "No TP", level: "⚡⚡⚡", content: "You are in the stall. There is no toilet paper. This is the end.", num: "20", color: "Panic Brown", item: "Empty Roll" },
    { type: "shaky-chaos", icon: "🤪", headline: "Reply All", level: "⚡⚡⚡", content: "Someone just hit 'Reply All' to the whole company with a personal secret.", num: "999", color: "Oops Red", item: "Email" },
    { type: "shaky-chaos", icon: "🤪", headline: "Printer War", level: "⚡⚡⚡", content: "The printer is jammed again. It has become sentient and demands sacrifice.", num: "200", color: "Jam Grey", item: "Paper" },
    { type: "shaky-chaos", icon: "🤪", headline: "Secret Baby", level: "⚡⚡⚡", content: "The wildest rumor: Someone is having a secret baby with... the printer?", num: "44", color: "Crazy Pink", item: "Pacifier" },
    { type: "shaky-chaos", icon: "🤪", headline: "Fire Drill", level: "⚡⚡⚡", content: "Is it a fire? Is it a drill? Or did someone burn popcorn again?", num: "119", color: "Fire Orange", item: "Popcorn" },
    { type: "shaky-chaos", icon: "🤪", headline: "Nap Time", level: "⚡⚡⚡", content: "Shaky found someone sleeping under their desk. Do not disturb.", num: "24", color: "Sleepy Blue", item: "Pillow" },
    { type: "shaky-chaos", icon: "🤪", headline: "Coffee Spill", level: "⚡⚡⚡", content: "You will spill coffee on your white shirt. It is art now. Own it.", num: "55", color: "Stain Brown", item: "Shirt" },
    { type: "shaky-chaos", icon: "🤪", headline: "Love Triangle", level: "⚡⚡⚡", content: "Receptionist loves IT guy, but IT guy loves the Coffee Machine.", num: "123", color: "Drama Red", item: "Heart" },
    { type: "shaky-chaos", icon: "🤪", headline: "Zombie", level: "⚡⚡⚡", content: "The team looks like zombies today. Too much overtime. Send brains.", num: "28", color: "Dead Green", item: "Brain" },
    { type: "shaky-chaos", icon: "🤪", headline: "Pyramid Scheme", level: "⚡⚡⚡", content: "Karen from accounting is trying to sell you essential oils again. Run.", num: "333", color: "Oil Yellow", item: "Bottle" },
    { type: "shaky-chaos", icon: "🤪", headline: "CEO Shaky", level: "⚡⚡⚡", content: "New rumor: Shaky is actually the owner of the company. Bow down.", num: "777", color: "Boss Gold", item: "Crown" }
];

// ============================================
// CONFIGURATION
// ============================================
const contentData = {
    luck: {
        label: "LUCK",
        className: "btn-luck-sub",
        options: [
            { id: "today", text: "Daily Vibe", result: "" }, 
            { id: "year", text: "Yes or No", result: "" }, 
            { id: "future", text: "Universe Says", result: "" } 
        ]
    },
    love: {
        label: "LOVE",
        className: "btn-love",
        options: [
            { id: "crush", text: "Love Radar", result: "" },
            { id: "partner", text: "Your Move", result: "" },
            { id: "self", text: "Red Flags", result: "" }
        ]
    },
    career: {
        label: "CAREER",
        className: "btn-career",
        options: [
            { id: "job", text: "Money Bag", result: "" },
            { id: "wealth", text: "Boss Battle", result: "" },
            { id: "goal", text: "Office Tea", result: "" }
        ]
    }
};